import { vi } from 'vitest';

/**
 * Mock for agent: backend
 * Generated by AutomatosX v8.0.0 - 2025-11-14T03:07:09.880Z
 */

/**
 * Create mock backend
 */
export const mockBackend = () => {
  return {
    execute: vi.fn().mockResolvedValue({ success: true, output: {} }),
    validate: vi.fn().mockResolvedValue({ success: true, output: {} }),
    cleanup: vi.fn().mockResolvedValue({ success: true, output: {} }),
  };
};

/**
 * Create mock backend with custom behavior
 */
export const mockBackendWithBehavior = (
  behavior: Record<string, any>
) => {
  const baseMock = mockBackend();

  Object.entries(behavior).forEach(([method, impl]) => {
    if (baseMock[method as keyof typeof baseMock]) {
      (baseMock as any)[method] = vi.fn().mockImplementation(impl);
    }
  });

  return baseMock;
};

/**
 * Create failing mock backend
 */
export const mockBackendWithError = (error: Error) => {
  return {
    execute: vi.fn().mockRejectedValue(error),
    validate: vi.fn().mockRejectedValue(error),
    cleanup: vi.fn().mockRejectedValue(error),
  };
};
