import { vi } from 'vitest';

/**
 * Mock for agent: security
 * Generated by AutomatosX v8.0.0 - 2025-11-14T03:07:09.881Z
 */

/**
 * Create mock security
 */
export const mockSecurity = () => {
  return {
    execute: vi.fn().mockResolvedValue({ success: true, output: {} }),
    validate: vi.fn().mockResolvedValue({ success: true, output: {} }),
    cleanup: vi.fn().mockResolvedValue({ success: true, output: {} }),
  };
};

/**
 * Create mock security with custom behavior
 */
export const mockSecurityWithBehavior = (
  behavior: Record<string, any>
) => {
  const baseMock = mockSecurity();

  Object.entries(behavior).forEach(([method, impl]) => {
    if (baseMock[method as keyof typeof baseMock]) {
      (baseMock as any)[method] = vi.fn().mockImplementation(impl);
    }
  });

  return baseMock;
};

/**
 * Create failing mock security
 */
export const mockSecurityWithError = (error: Error) => {
  return {
    execute: vi.fn().mockRejectedValue(error),
    validate: vi.fn().mockRejectedValue(error),
    cleanup: vi.fn().mockRejectedValue(error),
  };
};
