// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Timestamp from "./Timestamp.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function parseMessageRole(str) {
  switch (str) {
    case "assistant" :
        return "assistant";
    case "system" :
        return "system";
    case "user" :
        return "user";
    default:
      return ;
  }
}

function messageRoleToString(role) {
  switch (role) {
    case "user" :
        return "user";
    case "assistant" :
        return "assistant";
    case "system" :
        return "system";
    
  }
}

function getMessageFromResult(result) {
  var msg = result.source;
  switch (msg.TAG) {
    case "VectorOnly" :
        return ;
    case "FtsOnly" :
    case "Hybrid" :
        return msg._0;
    
  }
}

function getVectorFromResult(result) {
  var vr = result.source;
  switch (vr.TAG) {
    case "FtsOnly" :
        return ;
    case "VectorOnly" :
        return vr._0;
    case "Hybrid" :
        return vr._1;
    
  }
}

function isHybridResult(result) {
  var match = result.source;
  switch (match.TAG) {
    case "FtsOnly" :
    case "VectorOnly" :
        return false;
    case "Hybrid" :
        return true;
    
  }
}

var defaultWeights = {
  fts: 0.4,
  vector: 0.4,
  recency: 0.2
};

var defaultSearchOptions = {
  conversationId: undefined,
  limit: 10,
  weights: defaultWeights,
  minScore: 0.1
};

function makeSearchQuery(query, conversationIdOpt, optionsOpt, param) {
  var conversationId = conversationIdOpt !== undefined ? Caml_option.valFromOption(conversationIdOpt) : undefined;
  var options = optionsOpt !== undefined ? optionsOpt : defaultSearchOptions;
  return {
          query: query,
          conversationId: conversationId,
          options: options
        };
}

function isValidMessage(msg) {
  if (msg.id !== "") {
    return msg.content !== "";
  } else {
    return false;
  }
}

function areWeightsValid(weights) {
  var sum = weights.fts + weights.vector + weights.recency;
  if (sum >= 0.95) {
    return sum <= 1.05;
  } else {
    return false;
  }
}

function normalizeWeights(weights) {
  var sum = weights.fts + weights.vector + weights.recency;
  if (sum === 0.0) {
    return defaultWeights;
  } else {
    return {
            fts: weights.fts / sum,
            vector: weights.vector / sum,
            recency: weights.recency / sum
          };
  }
}

function calculateRecencyScore(timestamp) {
  var now = Timestamp.nowSeconds();
  var age = Timestamp.Seconds.toInt(Timestamp.Seconds.subtract(now, timestamp));
  return Math.exp((-age | 0) / 2592000);
}

function combineScores(ftsScore, vectorScore, recencyScore, weights) {
  var fts = Belt_Option.getWithDefault(ftsScore, 0.0);
  var vector = Belt_Option.getWithDefault(vectorScore, 0.0);
  return fts * weights.fts + vector * weights.vector + recencyScore * weights.recency;
}

export {
  parseMessageRole ,
  messageRoleToString ,
  getMessageFromResult ,
  getVectorFromResult ,
  isHybridResult ,
  defaultWeights ,
  defaultSearchOptions ,
  makeSearchQuery ,
  isValidMessage ,
  areWeightsValid ,
  normalizeWeights ,
  calculateRecencyScore ,
  combineScores ,
}
/* No side effect */
