// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Array from "@rescript/core/lib/es6/src/Core__Array.mjs";
import * as Core__Option from "@rescript/core/lib/es6/src/Core__Option.mjs";

function hasCycle(nodes) {
  var nodeMap = new Map();
  nodes.forEach(function (n) {
        nodeMap.set(n.id, n);
      });
  var visited = new Set();
  var recStack = new Set();
  var dfs = function (nodeId) {
    if (recStack.has(nodeId)) {
      return true;
    }
    if (visited.has(nodeId)) {
      return false;
    }
    visited.add(nodeId);
    recStack.add(nodeId);
    var node = nodeMap.get(nodeId);
    var hasCycleInDeps = node !== undefined ? node.deps.some(function (dep) {
            return dfs(dep);
          }) : false;
    recStack.delete(nodeId);
    return hasCycleInDeps;
  };
  return nodes.some(function (n) {
              return dfs(n.id);
            });
}

function findCriticalPath(nodes) {
  var nodeMap = new Map();
  nodes.forEach(function (n) {
        nodeMap.set(n.id, n);
      });
  var longestPath = new Map();
  var pathPredecessor = new Map();
  var inDegree = new Map();
  nodes.forEach(function (n) {
        inDegree.set(n.id, n.deps.length);
      });
  var queue = nodes.filter(function (n) {
          return n.deps.length === 0;
        }).map(function (n) {
        return n.id;
      });
  var sorted = [];
  var queueRef = {
    contents: queue
  };
  while(queueRef.contents.length > 0) {
    var c = queueRef.contents[0];
    var current = c !== undefined ? c : "";
    queueRef.contents = queueRef.contents.slice(1);
    if (current !== "") {
      sorted.push(current);
      nodes.forEach((function(current){
          return function (n) {
            if (!n.deps.includes(current)) {
              return ;
            }
            var newDegree = Core__Option.getOr(inDegree.get(n.id), 0) - 1 | 0;
            inDegree.set(n.id, newDegree);
            if (newDegree === 0) {
              queueRef.contents = queueRef.contents.concat([n.id]);
              return ;
            }
            
          }
          }(current)));
    }
    
  };
  if (sorted.length !== nodes.length) {
    return [];
  }
  sorted.forEach(function (nodeId) {
        var node = nodeMap.get(nodeId);
        if (node === undefined) {
          return ;
        }
        var maxPredDuration = Core__Array.reduce(node.deps, 0, (function (max, dep) {
                var depDuration = Core__Option.getOr(longestPath.get(dep), 0);
                if (depDuration > max) {
                  pathPredecessor.set(nodeId, dep);
                  return depDuration;
                } else {
                  return max;
                }
              }));
        longestPath.set(nodeId, maxPredDuration + node.estimatedDuration | 0);
      });
  var match = Core__Array.reduce(nodes, [
        "",
        0
      ], (function (param, node) {
          var maxDuration = param[1];
          var duration = Core__Option.getOr(longestPath.get(node.id), 0);
          if (duration > maxDuration) {
            return [
                    node.id,
                    duration
                  ];
          } else {
            return [
                    param[0],
                    maxDuration
                  ];
          }
        }));
  var endNode = match[0];
  if (endNode === "") {
    return [];
  }
  var path = [endNode];
  var current$1 = endNode;
  while(pathPredecessor.has(current$1)) {
    var pred = pathPredecessor.get(current$1);
    if (pred !== undefined) {
      path.unshift(pred);
      current$1 = pred;
    }
    
  };
  return path;
}

function scheduleParallel(nodes) {
  if (hasCycle(nodes)) {
    return {
            groups: [],
            totalEstimatedDuration: 0,
            criticalPath: [],
            error: "Cycle detected in DAG"
          };
  }
  if (nodes.length === 0) {
    return {
            groups: [],
            totalEstimatedDuration: 0,
            criticalPath: [],
            error: undefined
          };
  }
  var nodeMap = new Map();
  nodes.forEach(function (n) {
        nodeMap.set(n.id, n);
      });
  var remaining = nodes.map(function (n) {
        return n.id;
      });
  var completed = new Set();
  var groups = [];
  var totalDuration = 0;
  var continueLoop = true;
  while(remaining.length > 0 && continueLoop) {
    var ready = remaining.filter(function (nodeId) {
          var node = nodeMap.get(nodeId);
          if (node !== undefined) {
            return node.deps.every(function (dep) {
                        return completed.has(dep);
                      });
          } else {
            return false;
          }
        });
    if (ready.length === 0) {
      continueLoop = false;
    } else {
      var sortedReady = ready.toSorted(function (a, b) {
            var n = nodeMap.get(a);
            var priorityA = n !== undefined ? n.priority : 5;
            var n$1 = nodeMap.get(b);
            var priorityB = n$1 !== undefined ? n$1.priority : 5;
            return priorityA - priorityB | 0;
          });
      var groupDuration = Core__Array.reduce(sortedReady, 0, (function (max, nodeId) {
              var node = nodeMap.get(nodeId);
              if (node !== undefined) {
                return Math.max(max, node.estimatedDuration);
              } else {
                return max;
              }
            }));
      groups.push({
            nodes: sortedReady,
            parallelizable: sortedReady.length > 1,
            estimatedDuration: groupDuration
          });
      totalDuration = totalDuration + groupDuration | 0;
      sortedReady.forEach(function (id) {
            completed.add(id);
          });
      remaining = remaining.filter((function(sortedReady){
          return function (id) {
            return !sortedReady.includes(id);
          }
          }(sortedReady)));
    }
  };
  return {
          groups: groups,
          totalEstimatedDuration: totalDuration,
          criticalPath: findCriticalPath(nodes),
          error: undefined
        };
}

function getExecutionOrder(result) {
  return result.groups.flatMap(function (g) {
              return g.nodes;
            });
}

export {
  hasCycle ,
  findCriticalPath ,
  scheduleParallel ,
  getExecutionOrder ,
}
/* No side effect */
