// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Array from "@rescript/core/lib/es6/src/Core__Array.mjs";

var defaultContext_preferredTypes = [];

var defaultContext_preferredTags = [];

var defaultContext = {
  preferredTypes: defaultContext_preferredTypes,
  preferredTags: defaultContext_preferredTags,
  recencyWeight: 0.2,
  frequencyWeight: 0.15,
  importanceWeight: 0.25,
  ftsWeight: 0.4
};

function calculateRecencyScore(createdAt, now) {
  if (createdAt > now) {
    return 1.0;
  }
  var ageMs = now - createdAt;
  var ageDays = ageMs / (1000.0 * 60.0 * 60.0 * 24.0);
  return Math.pow(0.5, ageDays / 7.0);
}

function calculateFrequencyScore(accessCount) {
  if (accessCount <= 0) {
    return 0.0;
  } else {
    return Math.min(1.0, Math.log10(accessCount + 1.0) / 2.0);
  }
}

function calculateTypeBonus(entryType, preferredTypes) {
  if (preferredTypes.length === 0) {
    return 0.0;
  } else if (preferredTypes.includes(entryType)) {
    return 0.2;
  } else {
    return 0.0;
  }
}

function calculateTagBonus(tags, preferredTags) {
  if (preferredTags.length === 0 || tags.length === 0) {
    return 0.0;
  }
  var matchCount = tags.filter(function (t) {
        return preferredTags.includes(t);
      }).length;
  var maxMatches = Math.min(tags.length, preferredTags.length);
  if (maxMatches > 0) {
    return matchCount / maxMatches * 0.15;
  } else {
    return 0.0;
  }
}

function normalizeFtsScore(score, maxScore) {
  if (maxScore >= - 1e-10) {
    return 0.0;
  }
  if (score > 0.0) {
    return 1.0;
  }
  var absMaxScore = Math.abs(maxScore);
  var safeAbsMaxScore = absMaxScore === 0.0 ? 1e-10 : absMaxScore;
  var normalized = 1.0 + score / safeAbsMaxScore;
  return Math.min(1.0, Math.max(0.0, normalized));
}

function rankEntry(entry, ctx, now, maxFtsScore) {
  var ftsNormalized = normalizeFtsScore(entry.ftsScore, maxFtsScore);
  var recencyScore = calculateRecencyScore(entry.createdAt, now);
  var frequencyScore = calculateFrequencyScore(entry.accessCount);
  var typeBonus = calculateTypeBonus(entry.entryType, ctx.preferredTypes);
  var tagBonus = calculateTagBonus(entry.tags, ctx.preferredTags);
  var weightedScore = ftsNormalized * ctx.ftsWeight + recencyScore * ctx.recencyWeight + frequencyScore * ctx.frequencyWeight + entry.importance * ctx.importanceWeight + typeBonus + tagBonus;
  return {
          entry: entry,
          score: weightedScore,
          breakdown: {
            fts: ftsNormalized,
            recency: recencyScore,
            frequency: frequencyScore,
            importance: entry.importance,
            typeBonus: typeBonus,
            tagBonus: tagBonus
          }
        };
}

function rankEntries(entries, ctx) {
  if (entries.length === 0) {
    return [];
  }
  var now = Date.now();
  var e = entries[0];
  var firstFtsScore = e !== undefined ? e.ftsScore : 0.0;
  var maxFtsScore = Core__Array.reduce(entries, firstFtsScore, (function (min, e) {
          return Math.min(min, e.ftsScore);
        }));
  var ranked = entries.map(function (e) {
        return rankEntry(e, ctx, now, maxFtsScore);
      });
  return ranked.toSorted(function (a, b) {
              if (a.score > b.score) {
                return -1.0;
              } else if (a.score < b.score) {
                return 1.0;
              } else {
                return 0.0;
              }
            });
}

function getTopRanked(entries, ctx, limit) {
  var arrayLen = entries.length;
  var maxLen = arrayLen > 0 ? arrayLen : 1;
  var validLimit = Math.max(1, Math.min(limit, maxLen));
  var ranked = rankEntries(entries, ctx);
  return ranked.slice(0, validLimit);
}

export {
  defaultContext ,
  calculateRecencyScore ,
  calculateFrequencyScore ,
  calculateTypeBonus ,
  calculateTagBonus ,
  normalizeFtsScore ,
  rankEntry ,
  rankEntries ,
  getTopRanked ,
}
/* No side effect */
