// Generated by ReScript, PLEASE EDIT WITH CARE


function calculateScore(provider, ctx) {
  if (!provider.healthy) {
    return -1000.0;
  }
  var priorityScore = 100.0 - provider.priority * 10.0;
  var rateLimitScore = (1.0 - provider.rateLimit) * 50.0;
  var latencyScore = Math.max(0, 5000 - provider.latencyMs | 0) / 100.0;
  var successScore = provider.successRate * 100.0;
  var mcpBonus = ctx.preferMcp && provider.integrationMode === "mcp" ? 25.0 : 0.0;
  var complexityFactor = ctx.complexity > 7 ? provider.successRate * 20.0 : 0.0;
  return priorityScore + rateLimitScore + latencyScore + successScore + mcpBonus + complexityFactor;
}

function getScoreReason(provider, score, ctx) {
  if (provider.healthy) {
    if (score > 200.0) {
      return "Excellent: high success rate, low latency";
    } else if (score > 150.0) {
      if (ctx.preferMcp && provider.integrationMode === "mcp") {
        return "Good: MCP provider with good metrics";
      } else {
        return "Good: balanced performance metrics";
      }
    } else if (score > 100.0) {
      return "Acceptable: meets minimum requirements";
    } else {
      return "Fallback: other providers unavailable";
    }
  } else {
    return "Provider is unhealthy";
  }
}

function selectProvider(providers, ctx) {
  var forcedId = ctx.forceProvider;
  if (forcedId !== undefined) {
    var p = providers.find(function (p) {
          return p.id === forcedId;
        });
    if (p !== undefined) {
      return {
              provider: p,
              score: 1000.0,
              reason: "Forced provider selection",
              alternatives: []
            };
    } else {
      return {
              provider: undefined,
              score: 0.0,
              reason: "Forced provider '" + forcedId + "' not found",
              alternatives: []
            };
    }
  }
  var available = providers.filter(function (p) {
        return !ctx.excludeProviders.includes(p.id);
      });
  var scored = available.map(function (p) {
        var score = calculateScore(p, ctx);
        var reason = getScoreReason(p, score, ctx);
        return {
                provider: p,
                score: score,
                reason: reason
              };
      });
  var sorted = scored.toSorted(function (a, b) {
        if (a.score > b.score) {
          return -1.0;
        } else if (a.score < b.score) {
          return 1.0;
        } else {
          return 0.0;
        }
      });
  var valid = sorted.filter(function (sp) {
        return sp.score > 0.0;
      });
  var best = valid[0];
  if (best !== undefined) {
    return {
            provider: best.provider,
            score: best.score,
            reason: best.reason,
            alternatives: valid.slice(1).slice(0, 3)
          };
  } else {
    return {
            provider: undefined,
            score: 0.0,
            reason: "No healthy providers available",
            alternatives: []
          };
  }
}

function getFallbackOrder(providers, ctx) {
  return providers.filter(function (p) {
                    if (p.healthy) {
                      return !ctx.excludeProviders.includes(p.id);
                    } else {
                      return false;
                    }
                  }).map(function (p) {
                  return [
                          p,
                          calculateScore(p, ctx)
                        ];
                }).toSorted(function (param, param$1) {
                var b = param$1[1];
                var a = param[1];
                if (a > b) {
                  return -1.0;
                } else if (a < b) {
                  return 1.0;
                } else {
                  return 0.0;
                }
              }).map(function (param) {
              return param[0];
            });
}

export {
  calculateScore ,
  getScoreReason ,
  selectProvider ,
  getFallbackOrder ,
}
/* No side effect */
