// Generated by ReScript, PLEASE EDIT WITH CARE


var Hello;

var version = "2.0.0-alpha.0";

var name = "AutomatosX v2 - ReScript Core";

export {
  Hello ,
  version ,
  name ,
}
/* No side effect */
