// Generated by ReScript, PLEASE EDIT WITH CARE

import * as StateMachineV2 from "./runtime/StateMachineV2.bs.js";

var Hello;

var StateMachineV2$1;

var WorkflowStateMachine;

var WorkflowTypes;

var version = "2.0.0-alpha.0";

var name = "AutomatosX v2 - ReScript Core";

var makeStateMachine = StateMachineV2.make;

var transitionStateMachine = StateMachineV2.transition;

var getCurrentState = StateMachineV2.getCurrentState;

var canTransition = StateMachineV2.canTransition;

var setContextData = StateMachineV2.setContextData;

var getContextData = StateMachineV2.getContextData;

var createCheckpoint = StateMachineV2.createCheckpoint;

var restoreFromCheckpoint = StateMachineV2.restoreFromCheckpoint;

export {
  Hello ,
  StateMachineV2$1 as StateMachineV2,
  WorkflowStateMachine ,
  WorkflowTypes ,
  version ,
  name ,
  makeStateMachine ,
  transitionStateMachine ,
  getCurrentState ,
  canTransition ,
  setContextData ,
  getContextData ,
  createCheckpoint ,
  restoreFromCheckpoint ,
}
/* No side effect */
