// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_array from "rescript/lib/es6/js_array.js";
import * as Js_string from "rescript/lib/es6/js_string.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function makeUserId(id) {
  if (id.length === 0) {
    return {
            TAG: "Error",
            _0: "User ID cannot be empty"
          };
  } else if (!Js_string.startsWith("user-", id) && !Js_string.startsWith("usr_", id)) {
    return {
            TAG: "Error",
            _0: "User ID must start with 'user-' or 'usr_'"
          };
  } else {
    return {
            TAG: "Ok",
            _0: id
          };
  }
}

function makeConversationId(id) {
  if (id.length === 0) {
    return {
            TAG: "Error",
            _0: "Conversation ID cannot be empty"
          };
  } else if (!Js_string.startsWith("conv-", id) && !Js_string.startsWith("cvs_", id)) {
    return {
            TAG: "Error",
            _0: "Conversation ID must start with 'conv-' or 'cvs_'"
          };
  } else {
    return {
            TAG: "Ok",
            _0: id
          };
  }
}

function makeMessageId(id) {
  if (id.length === 0) {
    return {
            TAG: "Error",
            _0: "Message ID cannot be empty"
          };
  } else if (!Js_string.startsWith("msg-", id) && !Js_string.startsWith("msg_", id)) {
    return {
            TAG: "Error",
            _0: "Message ID must start with 'msg-' or 'msg_'"
          };
  } else {
    return {
            TAG: "Ok",
            _0: id
          };
  }
}

function makeModelId(id) {
  if (id.length === 0) {
    return {
            TAG: "Error",
            _0: "Model ID cannot be empty"
          };
  } else {
    return {
            TAG: "Ok",
            _0: id
          };
  }
}

function parseRole(role) {
  switch (role) {
    case "assistant" :
        return {
                TAG: "Ok",
                _0: "assistant"
              };
    case "function" :
        return {
                TAG: "Ok",
                _0: "function"
              };
    case "system" :
        return {
                TAG: "Ok",
                _0: "system"
              };
    case "user" :
        return {
                TAG: "Ok",
                _0: "user"
              };
    default:
      return {
              TAG: "Error",
              _0: "Invalid role: " + role + ". Must be user, assistant, system, or function"
            };
  }
}

function makeMessageContent(text) {
  if (text.length === 0) {
    return {
            TAG: "Error",
            _0: "Message content cannot be empty"
          };
  } else if (text.length > 100000) {
    return {
            TAG: "Error",
            _0: "Message content too long (max 100,000 characters)"
          };
  } else {
    return {
            TAG: "Ok",
            _0: {
              text: text,
              isValid: true
            }
          };
  }
}

function makeTokenCount(count) {
  if (count < 0) {
    return {
            TAG: "Error",
            _0: "Token count must be non-negative, got " + String(count)
          };
  } else if (count > 200000) {
    return {
            TAG: "Error",
            _0: "Token count too high: " + String(count) + " (max 200,000)"
          };
  } else {
    return {
            TAG: "Ok",
            _0: count
          };
  }
}

function makeTimestamp(ms) {
  if (ms < 0) {
    return {
            TAG: "Error",
            _0: "Timestamp cannot be negative: " + String(ms)
          };
  } else {
    return {
            TAG: "Ok",
            _0: {
              milliseconds: ms,
              isValid: true
            }
          };
  }
}

function makeTemperature(value) {
  if (value < 0.0) {
    return {
            TAG: "Error",
            _0: "Temperature must be non-negative, got " + String(value)
          };
  } else if (value > 2.0) {
    return {
            TAG: "Error",
            _0: "Temperature must be <= 2.0, got " + String(value)
          };
  } else {
    return {
            TAG: "Ok",
            _0: value
          };
  }
}

function makeMaxTokens(value) {
  if (value < 1) {
    return {
            TAG: "Error",
            _0: "Max tokens must be positive, got " + String(value)
          };
  } else if (value > 200000) {
    return {
            TAG: "Error",
            _0: "Max tokens too high: " + String(value) + " (max 200,000)"
          };
  } else {
    return {
            TAG: "Ok",
            _0: value
          };
  }
}

function createMessage(id, convId, role, content, tokens, timestampMs, modelOpt) {
  var model = modelOpt !== undefined ? Caml_option.valFromOption(modelOpt) : undefined;
  var errors = [];
  var v = makeMessageId(id);
  var validId;
  if (v.TAG === "Ok") {
    validId = v._0;
  } else {
    Js_array.push(v._0, errors);
    validId = undefined;
  }
  var v$1 = makeConversationId(convId);
  var validConvId;
  if (v$1.TAG === "Ok") {
    validConvId = v$1._0;
  } else {
    Js_array.push(v$1._0, errors);
    validConvId = undefined;
  }
  var v$2 = parseRole(role);
  var validRole;
  if (v$2.TAG === "Ok") {
    validRole = v$2._0;
  } else {
    Js_array.push(v$2._0, errors);
    validRole = undefined;
  }
  var v$3 = makeMessageContent(content);
  var validContent;
  if (v$3.TAG === "Ok") {
    validContent = v$3._0;
  } else {
    Js_array.push(v$3._0, errors);
    validContent = undefined;
  }
  var v$4 = makeTokenCount(tokens);
  var validTokens;
  if (v$4.TAG === "Ok") {
    validTokens = v$4._0;
  } else {
    Js_array.push(v$4._0, errors);
    validTokens = undefined;
  }
  var v$5 = makeTimestamp(timestampMs);
  var validTimestamp;
  if (v$5.TAG === "Ok") {
    validTimestamp = v$5._0;
  } else {
    Js_array.push(v$5._0, errors);
    validTimestamp = undefined;
  }
  var validModelId;
  if (model !== undefined) {
    var v$6 = makeModelId(model);
    if (v$6.TAG === "Ok") {
      validModelId = Caml_option.some(v$6._0);
    } else {
      Js_array.push(v$6._0, errors);
      validModelId = undefined;
    }
  } else {
    validModelId = Caml_option.some(undefined);
  }
  if (validId !== undefined && validConvId !== undefined && validRole !== undefined && validContent !== undefined && validTokens !== undefined && validTimestamp !== undefined && validModelId !== undefined) {
    return {
            TAG: "Ok",
            _0: {
              id: validId,
              conversationId: validConvId,
              role: validRole,
              content: validContent,
              tokens: validTokens,
              timestamp: validTimestamp,
              modelId: Caml_option.valFromOption(validModelId)
            }
          };
  } else {
    return {
            TAG: "Error",
            _0: errors
          };
  }
}

function unwrapUserId(id) {
  return id;
}

function unwrapConversationId(id) {
  return id;
}

function unwrapMessageId(id) {
  return id;
}

function unwrapModelId(id) {
  return id;
}

export {
  makeUserId ,
  makeConversationId ,
  makeMessageId ,
  makeModelId ,
  parseRole ,
  makeMessageContent ,
  makeTokenCount ,
  makeTimestamp ,
  makeTemperature ,
  makeMaxTokens ,
  createMessage ,
  unwrapUserId ,
  unwrapConversationId ,
  unwrapMessageId ,
  unwrapModelId ,
}
/* No side effect */
