#!/bin/bash
# AutomatosX Interactive CLI - Comprehensive Demo
# This script demonstrates all the features of ax-cli

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║   AutomatosX Interactive CLI - Feature Demo              ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "This demo showcases:"
echo "  ✓ Slash commands (/help, /agents, /save, /list, /load)"
echo "  ✓ AI conversations (mock mode)"
echo "  ✓ Agent delegation (@agent task syntax)"
echo "  ✓ Conversation persistence"
echo "  ✓ History management"
echo ""
echo "Press Enter to start..."
read

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "Step 1: Starting ax-cli (Mock Mode)"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Command: node dist/index.js cli"
echo ""
echo "The CLI will start in mock mode by default (no API keys needed)"
echo "Press Ctrl+C when you see the 'ax>' prompt to continue..."
echo ""
sleep 2

# We can't actually run interactive mode in a script, so we'll show what happens
cat << 'EOF'

Simulating ax-cli startup...

╭───────────────────────────────────────────╮
│   AutomatosX Interactive CLI v0.1.0       │
│   Type /help for commands, /exit to quit  │
│   Using: Gemini 1.5 Pro (simulated)      │
╰───────────────────────────────────────────╯

ax>

EOF

echo "═══════════════════════════════════════════════════════════"
echo "Step 2: Testing Slash Commands"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Available commands:"
echo "  /help     - Show all commands"
echo "  /agents   - List available agents"
echo "  /history  - Show conversation history"
echo "  /save     - Save conversation with a name"
echo "  /list     - List saved conversations"
echo "  /load     - Load a saved conversation"
echo "  /new      - Start new conversation"
echo "  /clear    - Clear screen"
echo "  /provider - Show current provider"
echo "  /exit     - Exit ax-cli"
echo ""
echo "Press Enter to see /agents command demo..."
read

echo ""
echo "Command: /agents"
echo ""
printf "/agents\n/exit\n" | node dist/index.js cli 2>&1 | grep -A 20 "Available Agents" | head -25

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "Step 3: Agent Delegation Syntax"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "You can delegate tasks to specific agents using:"
echo "  @backend implement authentication"
echo "  @frontend create login form"
echo "  @security audit the code"
echo ""
echo "Or use the alternative syntax:"
echo "  DELEGATE TO backend: implement authentication"
echo ""
echo "The agent will execute the task and show results."
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "Step 4: Conversation Management"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Conversations are automatically saved every 30 seconds."
echo ""
echo "Manual save: /save my-conversation"
echo "  → Saves to: .automatosx/cli-conversations/"
echo ""
echo "List saved: /list"
echo "  → Shows all saved conversations with details"
echo ""
echo "Load conversation: /load my-conversation"
echo "  → Restores messages and context"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "Step 5: Mock Mode vs Real Mode"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "MOCK MODE (Default - No API keys needed):"
echo "  node dist/index.js cli"
echo "  or"
echo "  AUTOMATOSX_MOCK_PROVIDERS=true node dist/index.js cli"
echo ""
echo "  • Simulated AI responses"
echo "  • Mock agent execution"
echo "  • Perfect for testing and demos"
echo ""
echo "REAL MODE (Requires setup):"
echo "  AUTOMATOSX_MOCK_PROVIDERS=false node dist/index.js cli"
echo ""
echo "  • Real Gemini API responses"
echo "  • Actual agent execution"
echo "  • Requires: gemini CLI + agent profiles"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "Step 6: Example Workflow"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "1. Start ax-cli:"
echo "   $ ax cli"
echo ""
echo "2. Ask a question:"
echo "   ax> How do I implement JWT authentication?"
echo "   AI: [Provides guidance on JWT implementation...]"
echo ""
echo "3. Delegate to an agent:"
echo "   ax> @backend implement JWT authentication with refresh tokens"
echo "   [@backend] Starting task..."
echo "   [@backend] Step 1/5: Installing dependencies..."
echo "   [@backend] ✓ Implementation complete!"
echo ""
echo "4. Save the conversation:"
echo "   ax> /save jwt-auth-session"
echo "   ✓ Conversation saved as: jwt-auth-session"
echo ""
echo "5. Later, load it back:"
echo "   ax> /load jwt-auth-session"
echo "   ✓ Loaded conversation: jwt-auth-session"
echo "   ℹ 12 messages loaded"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "Step 7: Advanced Features (Coming Soon)"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Phase 1 (Future):"
echo "  □ SQLite persistence (currently JSON files)"
echo "  □ Markdown rendering with syntax highlighting"
echo "  □ Memory search integration"
echo "  □ Code block extraction"
echo "  □ Multi-provider switching"
echo ""
echo "Phase 2+:"
echo "  □ VSCode extension integration"
echo "  □ MCP server support"
echo "  □ Team collaboration features"
echo "  □ Custom agent templates"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "Try It Yourself!"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Ready to try ax-cli? Run:"
echo ""
echo "  $ node dist/index.js cli"
echo ""
echo "or if installed:"
echo ""
echo "  $ ax cli"
echo "  $ ax interactive"
echo "  $ ax chat"
echo ""
echo "Quick commands to try:"
echo "  • /help          → See all commands"
echo "  • /agents        → List available agents"
echo "  • Hello!         → Get an AI response"
echo "  • @backend test  → Test agent delegation"
echo "  • /save demo     → Save your session"
echo "  • /list          → See saved conversations"
echo ""
echo "Documentation:"
echo "  • README: packages/cli-interactive/README.md"
echo "  • PRD: automatosx/PRD/ax-cli-final-prd.md"
echo "  • Integration: automatosx/PRD/INTEGRATION-COMPLETE.md"
echo ""
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║   Demo Complete! Happy coding with AutomatosX! 🚀        ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
