// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Js_string from "rescript/lib/es6/js_string.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function makeUserId(id) {
  if (id.length === 0) {
    return {
            TAG: "Error",
            _0: "User ID cannot be empty"
          };
  } else if (Js_string.startsWith("user-", id)) {
    return {
            TAG: "Ok",
            _0: {
              TAG: "UserId",
              _0: id
            }
          };
  } else {
    return {
            TAG: "Error",
            _0: "User ID must start with 'user-': " + id
          };
  }
}

function makeConversationId(id) {
  if (id.length === 0) {
    return {
            TAG: "Error",
            _0: "Conversation ID cannot be empty"
          };
  } else if (Js_string.startsWith("conv-", id)) {
    return {
            TAG: "Ok",
            _0: {
              TAG: "ConversationId",
              _0: id
            }
          };
  } else {
    return {
            TAG: "Error",
            _0: "Conversation ID must start with 'conv-': " + id
          };
  }
}

function makeMessageId(id) {
  if (id.length === 0) {
    return {
            TAG: "Error",
            _0: "Message ID cannot be empty"
          };
  } else if (Js_string.startsWith("msg-", id)) {
    return {
            TAG: "Ok",
            _0: {
              TAG: "MessageId",
              _0: id
            }
          };
  } else {
    return {
            TAG: "Error",
            _0: "Message ID must start with 'msg-': " + id
          };
  }
}

function makeModelId(id) {
  if (id.length === 0) {
    return {
            TAG: "Error",
            _0: "Model ID cannot be empty"
          };
  } else {
    return {
            TAG: "Ok",
            _0: {
              TAG: "ModelId",
              _0: id
            }
          };
  }
}

function makeSessionId(id) {
  if (id.length === 0) {
    return {
            TAG: "Error",
            _0: "Session ID cannot be empty"
          };
  } else {
    return {
            TAG: "Ok",
            _0: {
              TAG: "SessionId",
              _0: id
            }
          };
  }
}

function makeTokenId(id) {
  if (id.length === 0) {
    return {
            TAG: "Error",
            _0: "Token ID cannot be empty"
          };
  } else {
    return {
            TAG: "Ok",
            _0: {
              TAG: "TokenId",
              _0: id
            }
          };
  }
}

function unsafeUserId(id) {
  return {
          TAG: "UserId",
          _0: id
        };
}

function unsafeConversationId(id) {
  return {
          TAG: "ConversationId",
          _0: id
        };
}

function unsafeMessageId(id) {
  return {
          TAG: "MessageId",
          _0: id
        };
}

function unsafeModelId(id) {
  return {
          TAG: "ModelId",
          _0: id
        };
}

function unsafeSessionId(id) {
  return {
          TAG: "SessionId",
          _0: id
        };
}

function unsafeTokenId(id) {
  return {
          TAG: "TokenId",
          _0: id
        };
}

function unwrapUserId(id) {
  return id._0;
}

function unwrapConversationId(id) {
  return id._0;
}

function unwrapMessageId(id) {
  return id._0;
}

function unwrapModelId(id) {
  return id._0;
}

function unwrapSessionId(id) {
  return id._0;
}

function unwrapTokenId(id) {
  return id._0;
}

function eqUserId(a, b) {
  return a._0 === b._0;
}

function eqConversationId(a, b) {
  return a._0 === b._0;
}

function eqMessageId(a, b) {
  return a._0 === b._0;
}

function eqModelId(a, b) {
  return a._0 === b._0;
}

function eqSessionId(a, b) {
  return a._0 === b._0;
}

function eqTokenId(a, b) {
  return a._0 === b._0;
}

function makeTokenCount(count) {
  if (count < 0) {
    return {
            TAG: "Error",
            _0: "Token count must be non-negative, got " + String(count)
          };
  } else {
    return {
            TAG: "Ok",
            _0: {
              TAG: "TokenCount",
              _0: count
            }
          };
  }
}

function unwrapTokenCount(count) {
  return count._0;
}

function makeTimestamp(ms) {
  if (ms < 0) {
    return {
            TAG: "Error",
            _0: "Timestamp cannot be negative: " + String(ms)
          };
  } else {
    return {
            TAG: "Ok",
            _0: {
              TAG: "Timestamp",
              _0: ms
            }
          };
  }
}

function unwrapTimestamp(ms) {
  return ms._0;
}

function now() {
  return {
          TAG: "Timestamp",
          _0: Date.now() | 0
        };
}

function makePrice(cents) {
  if (cents < 0) {
    return {
            TAG: "Error",
            _0: "Price cannot be negative: " + String(cents)
          };
  } else {
    return {
            TAG: "Ok",
            _0: {
              TAG: "Price",
              _0: cents
            }
          };
  }
}

function unwrapPrice(cents) {
  return cents._0;
}

function dollarsToPrice(dollars) {
  return {
          TAG: "Price",
          _0: dollars * 100.0 | 0
        };
}

function priceToDollars(price) {
  return price._0 / 100.0;
}

function makeEmail(address) {
  if (address.length === 0) {
    return {
            TAG: "Error",
            _0: "Email cannot be empty"
          };
  } else if (Js_string.includes("@", address)) {
    return {
            TAG: "Ok",
            _0: {
              TAG: "Email",
              _0: address
            }
          };
  } else {
    return {
            TAG: "Error",
            _0: "Invalid email format: " + address
          };
  }
}

function unwrapEmail(address) {
  return address._0;
}

function makePhoneNumber(phone) {
  if (phone.length === 0) {
    return {
            TAG: "Error",
            _0: "Phone number cannot be empty"
          };
  }
  var phoneRegex = /^\+?[1-9]\d{9,14}$/;
  if (phoneRegex.test(phone)) {
    return {
            TAG: "Ok",
            _0: {
              TAG: "PhoneNumber",
              _0: phone
            }
          };
  } else {
    return {
            TAG: "Error",
            _0: "Invalid phone number format: " + phone
          };
  }
}

function unwrapPhoneNumber(phone) {
  return phone._0;
}

function makeUrl(address) {
  if (address.length === 0) {
    return {
            TAG: "Error",
            _0: "URL cannot be empty"
          };
  } else if (!Js_string.startsWith("http://", address) && !Js_string.startsWith("https://", address)) {
    return {
            TAG: "Error",
            _0: "Invalid URL format (must start with http:// or https://): " + address
          };
  } else {
    return {
            TAG: "Ok",
            _0: {
              TAG: "Url",
              _0: address
            }
          };
  }
}

function unwrapUrl(address) {
  return address._0;
}

function makeNonEmptyArray(arr) {
  if (arr.length === 0) {
    return {
            TAG: "Error",
            _0: "Array cannot be empty"
          };
  } else {
    return {
            TAG: "Ok",
            _0: {
              TAG: "NonEmptyArray",
              _0: arr
            }
          };
  }
}

function unwrapNonEmptyArray(arr) {
  return arr._0;
}

function headNonEmpty(arr) {
  var value = Belt_Array.get(arr._0, 0);
  if (value !== undefined) {
    return Caml_option.valFromOption(value);
  } else {
    return Js_exn.raiseError("Impossible: non-empty array is empty");
  }
}

function getUserConversations(uid) {
  return [];
}

function getConversationMessages(convId) {
  return [];
}

function userIdToString(id) {
  return "UserId(" + id._0 + ")";
}

function conversationIdToString(id) {
  return "ConversationId(" + id._0 + ")";
}

function messageIdToString(id) {
  return "MessageId(" + id._0 + ")";
}

export {
  makeUserId ,
  makeConversationId ,
  makeMessageId ,
  makeModelId ,
  makeSessionId ,
  makeTokenId ,
  unsafeUserId ,
  unsafeConversationId ,
  unsafeMessageId ,
  unsafeModelId ,
  unsafeSessionId ,
  unsafeTokenId ,
  unwrapUserId ,
  unwrapConversationId ,
  unwrapMessageId ,
  unwrapModelId ,
  unwrapSessionId ,
  unwrapTokenId ,
  eqUserId ,
  eqConversationId ,
  eqMessageId ,
  eqModelId ,
  eqSessionId ,
  eqTokenId ,
  makeTokenCount ,
  unwrapTokenCount ,
  makeTimestamp ,
  unwrapTimestamp ,
  now ,
  makePrice ,
  unwrapPrice ,
  dollarsToPrice ,
  priceToDollars ,
  makeEmail ,
  unwrapEmail ,
  makePhoneNumber ,
  unwrapPhoneNumber ,
  makeUrl ,
  unwrapUrl ,
  makeNonEmptyArray ,
  unwrapNonEmptyArray ,
  headNonEmpty ,
  getUserConversations ,
  getConversationMessages ,
  userIdToString ,
  conversationIdToString ,
  messageIdToString ,
}
/* No side effect */
