export {
  TraceEventTypeSchema,
  TraceStatusSchema,
  TraceContextSchema,
  RunStartPayloadSchema,
  RunEndPayloadSchema,
  RoutingDecisionPayloadSchema,
  StepExecutePayloadSchema,
  ErrorPayloadSchema,
  // Discussion trace payloads
  DiscussionStartPayloadSchema,
  DiscussionRoundPayloadSchema,
  DiscussionProviderPayloadSchema,
  DiscussionConsensusPayloadSchema,
  DiscussionEndPayloadSchema,
  TraceEventSchema,
  TraceSchema,
  createTraceEvent,
  createTrace,
  validateTraceEvent,
  safeValidateTraceEvent,
  validateTrace,
  isTraceComplete,
  getOrderedEvents,
  type TraceEventType,
  type TraceStatus,
  type TraceContext,
  type RunStartPayload,
  type RunEndPayload,
  type RoutingDecisionPayload,
  type StepExecutePayload,
  type ErrorPayload,
  // Discussion trace types
  type DiscussionStartPayload,
  type DiscussionRoundPayload,
  type DiscussionProviderPayload,
  type DiscussionConsensusPayload,
  type DiscussionEndPayload,
  type TraceEvent,
  type Trace,
} from './schema.js';
