export {
  TraceEventTypeSchema,
  TraceStatusSchema,
  TraceContextSchema,
  RunStartPayloadSchema,
  RunEndPayloadSchema,
  RoutingDecisionPayloadSchema,
  StepExecutePayloadSchema,
  ErrorPayloadSchema,
  // Discussion trace payloads
  DiscussionStartPayloadSchema,
  DiscussionRoundPayloadSchema,
  DiscussionProviderPayloadSchema,
  DiscussionConsensusPayloadSchema,
  DiscussionEndPayloadSchema,
  TraceEventSchema,
  TraceSchema,
  // Classification schemas (PRD-2026-003)
  ClassificationGuardResultSchema,
  ClassificationAlternativeSchema,
  TaskClassificationSnapshotSchema,
  ClassificationMetricsSchema,
  createTraceEvent,
  createTrace,
  validateTraceEvent,
  safeValidateTraceEvent,
  validateTrace,
  isTraceComplete,
  getOrderedEvents,
  // Trace hierarchy functions (INV-TR-020 through INV-TR-024)
  createRootTraceHierarchy,
  createChildTraceHierarchy,
  extractTraceHierarchy,
  type TraceEventType,
  type TraceStatus,
  type TraceContext,
  type RunStartPayload,
  type RunEndPayload,
  type RoutingDecisionPayload,
  type StepExecutePayload,
  type ErrorPayload,
  // Discussion trace types
  type DiscussionStartPayload,
  type DiscussionRoundPayload,
  type DiscussionProviderPayload,
  type DiscussionConsensusPayload,
  type DiscussionEndPayload,
  type TraceEvent,
  type Trace,
  // Trace hierarchy type
  type TraceHierarchy,
  // Classification types (PRD-2026-003)
  type ClassificationGuardResult,
  type ClassificationAlternative,
  type TaskClassificationSnapshot,
  type ClassificationMetrics,
} from './schema.js';
