export const WorkflowErrorCodes = {
    VALIDATION_ERROR: 'WORKFLOW_VALIDATION_ERROR',
    DUPLICATE_STEP_ID: 'WORKFLOW_DUPLICATE_STEP_ID',
    STEP_EXECUTION_FAILED: 'WORKFLOW_STEP_EXECUTION_FAILED',
    STEP_TIMEOUT: 'WORKFLOW_STEP_TIMEOUT',
    MAX_RETRIES_EXCEEDED: 'WORKFLOW_MAX_RETRIES_EXCEEDED',
    UNKNOWN_STEP_TYPE: 'WORKFLOW_UNKNOWN_STEP_TYPE',
    AFTER_GUARD_ERROR: 'WORKFLOW_AFTER_GUARD_ERROR',
};
