// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";

function create() {
  return {};
}

function getRefillRate() {
  return 10.0 / 60000.0;
}

function getBucket(limiter, userId) {
  var bucket = Js_dict.get(limiter, userId);
  if (bucket !== undefined) {
    return bucket;
  }
  var now = Date.now();
  var newBucket_refillRate = 10.0 / 60000.0;
  var newBucket = {
    tokens: 10.0,
    lastRefill: now,
    maxTokens: 10.0,
    refillRate: newBucket_refillRate
  };
  limiter[userId] = newBucket;
  return newBucket;
}

function refillBucket(bucket, now) {
  var elapsed = now - bucket.lastRefill;
  var tokensToAdd = elapsed * bucket.refillRate;
  var newTokens = Math.min(bucket.tokens + tokensToAdd, bucket.maxTokens);
  return {
          tokens: newTokens,
          lastRefill: now,
          maxTokens: bucket.maxTokens,
          refillRate: bucket.refillRate
        };
}

function tryConsume(limiter, userId) {
  var now = Date.now();
  var bucket = getBucket(limiter, userId);
  var refilled = refillBucket(bucket, now);
  if (refilled.tokens >= 1.0) {
    var consumed_tokens = refilled.tokens - 1.0;
    var consumed_lastRefill = refilled.lastRefill;
    var consumed_maxTokens = refilled.maxTokens;
    var consumed_refillRate = refilled.refillRate;
    var consumed = {
      tokens: consumed_tokens,
      lastRefill: consumed_lastRefill,
      maxTokens: consumed_maxTokens,
      refillRate: consumed_refillRate
    };
    limiter[userId] = consumed;
    return true;
  }
  limiter[userId] = refilled;
  return false;
}

function getTokens(limiter, userId) {
  var now = Date.now();
  var bucket = getBucket(limiter, userId);
  return refillBucket(bucket, now).tokens;
}

var RateLimiter = {
  create: create,
  maxCancellationsPerMinute: 10.0,
  windowMs: 60000.0,
  getRefillRate: getRefillRate,
  getBucket: getBucket,
  refillBucket: refillBucket,
  tryConsume: tryConsume,
  getTokens: getTokens
};

function requiresConfirmation(state) {
  if (state === "Executing") {
    return true;
  } else {
    return false;
  }
}

function createRequirement(state) {
  if (requiresConfirmation(state)) {
    return {
            TAG: "Required",
            requestedAt: Date.now()
          };
  } else {
    return "NotRequired";
  }
}

function confirm(status) {
  if (typeof status !== "object" || status.TAG !== "Required") {
    return status;
  } else {
    return {
            TAG: "Confirmed",
            requestedAt: status.requestedAt,
            confirmedAt: Date.now()
          };
  }
}

function isConfirmed(status) {
  if (typeof status !== "object" || status.TAG !== "Required") {
    return true;
  } else {
    return false;
  }
}

function isExpired(status, now) {
  if (typeof status !== "object") {
    return false;
  }
  if (status.TAG !== "Required") {
    return false;
  }
  var age = now - status.requestedAt;
  return age > 30000.0;
}

var ConfirmationRequired = {
  requiresConfirmation: requiresConfirmation,
  createRequirement: createRequirement,
  confirm: confirm,
  isConfirmed: isConfirmed,
  isExpired: isExpired
};

function create$1() {
  return [];
}

function append(log, entry) {
  return log.concat([entry]);
}

function getEntries(log) {
  return log;
}

function getCancellationCount(log, userId, windowMs) {
  var now = Date.now();
  var cutoff = now - windowMs;
  return log.filter(function (entry) {
              if (entry.userId === userId && entry.timestamp > cutoff) {
                return entry.allowed;
              } else {
                return false;
              }
            }).length;
}

var CancellationAudit = {
  create: create$1,
  append: append,
  getEntries: getEntries,
  getCancellationCount: getCancellationCount
};

function create$2() {
  return {
          rateLimiter: {},
          auditLog: []
        };
}

function checkCancellation(limiter, taskId, userId, state, confirmation) {
  var rateLimitPassed = tryConsume(limiter.rateLimiter, userId);
  if (rateLimitPassed) {
    var requiresConfirm = requiresConfirmation(state);
    if (requiresConfirm) {
      var now = Date.now();
      if (isExpired(confirmation, now)) {
        var entry_reason = "Confirmation expired";
        var entry = {
          taskId: taskId,
          userId: userId,
          state: state,
          timestamp: now,
          rateLimitPassed: true,
          confirmationRequired: true,
          confirmationProvided: false,
          allowed: false,
          reason: entry_reason
        };
        var newLog = limiter.auditLog.concat([entry]);
        var newLimiter_rateLimiter = limiter.rateLimiter;
        var newLimiter = {
          rateLimiter: newLimiter_rateLimiter,
          auditLog: newLog
        };
        return [
                newLimiter,
                "ConfirmationExpired"
              ];
      }
      if (isConfirmed(confirmation)) {
        var entry$1 = {
          taskId: taskId,
          userId: userId,
          state: state,
          timestamp: now,
          rateLimitPassed: true,
          confirmationRequired: true,
          confirmationProvided: true,
          allowed: true,
          reason: undefined
        };
        var newLog$1 = limiter.auditLog.concat([entry$1]);
        var newLimiter_rateLimiter$1 = limiter.rateLimiter;
        var newLimiter$1 = {
          rateLimiter: newLimiter_rateLimiter$1,
          auditLog: newLog$1
        };
        return [
                newLimiter$1,
                "Allowed"
              ];
      }
      var entry_reason$1 = "Confirmation required";
      var entry$2 = {
        taskId: taskId,
        userId: userId,
        state: state,
        timestamp: now,
        rateLimitPassed: true,
        confirmationRequired: true,
        confirmationProvided: false,
        allowed: false,
        reason: entry_reason$1
      };
      var newLog$2 = limiter.auditLog.concat([entry$2]);
      var newLimiter_rateLimiter$2 = limiter.rateLimiter;
      var newLimiter$2 = {
        rateLimiter: newLimiter_rateLimiter$2,
        auditLog: newLog$2
      };
      return [
              newLimiter$2,
              {
                TAG: "ConfirmationRequired",
                status: confirmation
              }
            ];
    }
    var entry_timestamp = Date.now();
    var entry$3 = {
      taskId: taskId,
      userId: userId,
      state: state,
      timestamp: entry_timestamp,
      rateLimitPassed: true,
      confirmationRequired: false,
      confirmationProvided: false,
      allowed: true,
      reason: undefined
    };
    var newLog$3 = limiter.auditLog.concat([entry$3]);
    var newLimiter_rateLimiter$3 = limiter.rateLimiter;
    var newLimiter$3 = {
      rateLimiter: newLimiter_rateLimiter$3,
      auditLog: newLog$3
    };
    return [
            newLimiter$3,
            "Allowed"
          ];
  }
  var tokens = getTokens(limiter.rateLimiter, userId);
  var retriesIn = (1.0 - tokens) / (10.0 / 60000.0);
  var entry_timestamp$1 = Date.now();
  var entry_reason$2 = "Rate limit exceeded";
  var entry$4 = {
    taskId: taskId,
    userId: userId,
    state: state,
    timestamp: entry_timestamp$1,
    rateLimitPassed: false,
    confirmationRequired: false,
    confirmationProvided: false,
    allowed: false,
    reason: entry_reason$2
  };
  var newLog$4 = limiter.auditLog.concat([entry$4]);
  var newLimiter_rateLimiter$4 = limiter.rateLimiter;
  var newLimiter$4 = {
    rateLimiter: newLimiter_rateLimiter$4,
    auditLog: newLog$4
  };
  return [
          newLimiter$4,
          {
            TAG: "RateLimitExceeded",
            userId: userId,
            retriesIn: retriesIn
          }
        ];
}

function getAuditLog(limiter) {
  return limiter.auditLog;
}

function getUserStats(limiter, userId) {
  var tokens = getTokens(limiter.rateLimiter, userId);
  var count = getCancellationCount(limiter.auditLog, userId, 60000.0);
  return [
          tokens,
          count
        ];
}

var CancellationLimiter = {
  create: create$2,
  checkCancellation: checkCancellation,
  getAuditLog: getAuditLog,
  getUserStats: getUserStats
};

var createLimiter = create$2;

var createConfirmationRequirement = createRequirement;

var confirmCancellation = confirm;

var isConfirmationComplete = isConfirmed;

var isConfirmationExpired = isExpired;

var maxCancellationsPerMinute = 10.0;

export {
  RateLimiter ,
  ConfirmationRequired ,
  CancellationAudit ,
  CancellationLimiter ,
  createLimiter ,
  checkCancellation ,
  getAuditLog ,
  getUserStats ,
  createConfirmationRequirement ,
  confirmCancellation ,
  isConfirmationComplete ,
  isConfirmationExpired ,
  maxCancellationsPerMinute ,
}
/* No side effect */
