/**
 * Usage Tracking Types
 *
 * Phase 3: Predictive limit detection with usage trends
 *
 * @module types/usage
 */

/**
 * Usage Entry - Single usage record
 */
export interface UsageEntry {
  id?: number;  // Auto-generated by database
  timestamp: number;
  provider: string;
  tokensUsed: number;
  requestsCount: number;
  windowStart: number;  // Hourly window start timestamp
}

/**
 * Usage Trends - Provider usage trends over time
 */
export interface UsageTrends {
  provider: string;
  window: number;  // hours
  requests: number;
  tokens: number;
  avgRequestsPerHour: number;
  avgTokensPerHour: number;
  trend: 'increasing' | 'stable' | 'decreasing';
}

/**
 * Known Provider Limits
 */
export interface ProviderLimits {
  tokensPerMinute?: number;
  requestsPerMinute?: number;
  requestsPerDay?: number;
  tokensPerDay?: number;
  requestsPerWeek?: number;
}

/**
 * Prediction Result
 */
export interface PredictionResult {
  provider: string;
  currentRate: {
    requestsPerHour: number;
    tokensPerHour: number;
  };
  knownLimits: ProviderLimits;
  prediction: {
    timeToExhaustionHours: number;
    status: 'healthy' | 'warning' | 'critical';
    shouldRotate: boolean;
  };
  confidence: number;  // 0-1
}

/**
 * Predictive Limit Configuration
 */
export interface PredictiveLimitConfig {
  enabled: boolean;
  trackingWindow: number;  // hours to track (default: 24)
  rotationThreshold: number;  // hours before exhaustion to rotate (default: 1)
  knownLimits: Record<string, ProviderLimits>;
}
