/**
 * Steps Fixtures
 * Generated by AutomatosX v8.0.0
 */

export const stepsFixtures = [
  {
    "id": "step-1",
    "name": "First Step",
    "agent": "backend",
    "action": "test-action",
    "config": {},
    "expectedOutput": {
      "success": true,
      "output": {},
      "duration": 7500
    }
  },
  {
    "id": "step-2",
    "name": "Second Step",
    "agent": "security",
    "action": "test-action",
    "config": {},
    "expectedOutput": {
      "success": true,
      "output": {},
      "duration": 15000
    }
  }
];

export const stepConfigs = {
  'step-1': {},
  'step-2': {}
};

export const stepExpectations = {
  'step-1': {
    success: true,
    duration: 7500,
    hasSideEffects: false,
  },
  'step-2': {
    success: true,
    duration: 15000,
    hasSideEffects: false,
  }
};
