// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as TaskStateMachine from "../runtime/TaskStateMachine.bs.js";

function toString(v) {
  if (typeof v !== "object") {
    return "null";
  }
  switch (v.TAG) {
    case "StringValue" :
        return "\"" + v._0 + "\"";
    case "IntValue" :
    case "FloatValue" :
        return String(v._0);
    case "BoolValue" :
        if (v._0) {
          return "true";
        } else {
          return "false";
        }
    case "ContextRef" :
        return "$" + v._0;
    
  }
}

function isLiteral(v) {
  if (typeof v !== "object" || v.TAG !== "ContextRef") {
    return true;
  } else {
    return false;
  }
}

function getTypeName(v) {
  if (typeof v !== "object") {
    return "null";
  }
  switch (v.TAG) {
    case "StringValue" :
        return "string";
    case "IntValue" :
        return "int";
    case "FloatValue" :
        return "float";
    case "BoolValue" :
        return "bool";
    case "ContextRef" :
        return "context_ref";
    
  }
}

var ValueHelpers = {
  toString: toString,
  isLiteral: isLiteral,
  getTypeName: getTypeName
};

function toString$1(op) {
  switch (op) {
    case "Equal" :
        return "==";
    case "NotEqual" :
        return "!=";
    case "GreaterThan" :
        return ">";
    case "LessThan" :
        return "<";
    case "GreaterThanOrEqual" :
        return ">=";
    case "LessThanOrEqual" :
        return "<=";
    case "Contains" :
        return "contains";
    case "Matches" :
        return "matches";
    
  }
}

function validateOperands(op, left, right) {
  switch (op) {
    case "Contains" :
        if (typeof left !== "object") {
          return false;
        }
        switch (left.TAG) {
          case "StringValue" :
              if (typeof right !== "object" || right.TAG !== "StringValue") {
                return false;
              } else {
                return true;
              }
          case "ContextRef" :
              return true;
          default:
            return false;
        }
    case "Matches" :
        if (typeof left !== "object") {
          return false;
        }
        switch (left.TAG) {
          case "StringValue" :
              if (typeof right !== "object" || right.TAG !== "StringValue") {
                return false;
              } else {
                return true;
              }
          case "ContextRef" :
              if (typeof right !== "object" || right.TAG !== "StringValue") {
                return false;
              } else {
                return true;
              }
          default:
            return false;
        }
    default:
      return true;
  }
}

var CompareOpHelpers = {
  toString: toString$1,
  validateOperands: validateOperands
};

function toString$2(cond) {
  if (typeof cond !== "object") {
    if (cond === "Always") {
      return "ALWAYS";
    } else {
      return "NEVER";
    }
  }
  switch (cond.TAG) {
    case "Comparison" :
        return toString(cond._0) + " " + toString$1(cond._1) + " " + toString(cond._2);
    case "LogicalOp" :
        if (cond._0 === "And") {
          return "(" + toString$2(cond._1) + " AND " + toString$2(cond._2) + ")";
        } else {
          return "(" + toString$2(cond._1) + " OR " + toString$2(cond._2) + ")";
        }
    case "Not" :
        return "NOT (" + toString$2(cond._0) + ")";
    
  }
}

function getContextRefs(_cond) {
  while(true) {
    var cond = _cond;
    if (typeof cond !== "object") {
      if (cond === "Always") {
        return [];
      } else {
        return [];
      }
    }
    switch (cond.TAG) {
      case "Comparison" :
          var right = cond._2;
          var left = cond._0;
          var leftRefs;
          leftRefs = typeof left !== "object" ? [] : (
              left.TAG === "ContextRef" ? [left._0] : []
            );
          var rightRefs;
          rightRefs = typeof right !== "object" ? [] : (
              right.TAG === "ContextRef" ? [right._0] : []
            );
          return Belt_Array.concat(leftRefs, rightRefs);
      case "LogicalOp" :
          return Belt_Array.concat(getContextRefs(cond._1), getContextRefs(cond._2));
      case "Not" :
          _cond = cond._0;
          continue ;
      
    }
  };
}

var ConditionHelpers = {
  toString: toString$2,
  getContextRefs: getContextRefs
};

function toString$3(action) {
  if (typeof action !== "object") {
    return "NoAction";
  }
  switch (action.TAG) {
    case "ExecuteEffect" :
        var effect = action._0;
        var effectStr;
        if (typeof effect !== "object") {
          switch (effect) {
            case "EvaluateGuards" :
                effectStr = "EvaluateGuards";
                break;
            case "EnterWaitState" :
                effectStr = "EnterWaitState";
                break;
            case "ScheduleRetry" :
                effectStr = "ScheduleRetry";
                break;
            case "FlushTelemetryBuffer" :
                effectStr = "FlushTelemetryBuffer";
                break;
            
          }
        } else {
          switch (effect.TAG) {
            case "HydratePlan" :
                effectStr = "HydratePlan(" + effect._0 + ")";
                break;
            case "StartExecution" :
                effectStr = "StartExecution(" + effect._0 + ")";
                break;
            case "EmitTelemetry" :
                effectStr = "EmitTelemetry(" + effect._0 + ")";
                break;
            case "PerformRollback" :
                effectStr = "PerformRollback(" + effect._0 + ")";
                break;
            case "RecordCancellation" :
                effectStr = "RecordCancellation(" + effect._0 + ")";
                break;
            
          }
        }
        return "ExecuteEffect(" + effectStr + ")";
    case "SetContextValue" :
        return "SetContext(" + action._0 + " = " + toString(action._1) + ")";
    case "TransitionTo" :
        return "TransitionTo(" + TaskStateMachine.State.toString(action._0) + ")";
    case "EmitEvent" :
        var $$event = action._0;
        var eventStr;
        if (typeof $$event !== "object") {
          switch ($$event) {
            case "DependenciesReady" :
                eventStr = "DependenciesReady";
                break;
            case "RetryTrigger" :
                eventStr = "RetryTrigger";
                break;
            case "TelemetryFlushed" :
                eventStr = "TelemetryFlushed";
                break;
            
          }
        } else {
          switch ($$event.TAG) {
            case "TaskSubmitted" :
                eventStr = "TaskSubmitted(" + $$event._0.taskId + ")";
                break;
            case "RuleViolation" :
                eventStr = "RuleViolation(" + $$event._0 + ")";
                break;
            case "Timeout" :
                eventStr = "Timeout(" + String($$event._0) + ")";
                break;
            case "CancelRequest" :
                eventStr = "CancelRequest(" + $$event._0.requestedBy + ")";
                break;
            
          }
        }
        return "EmitEvent(" + eventStr + ")";
    
  }
}

var ActionHelpers = {
  toString: toString$3
};

function toInt(p) {
  if (typeof p === "object") {
    return p._0;
  }
  switch (p) {
    case "High" :
        return 100;
    case "Medium" :
        return 50;
    case "Low" :
        return 10;
    
  }
}

function toString$4(p) {
  if (typeof p === "object") {
    return "Custom(" + String(p._0) + ")";
  }
  switch (p) {
    case "High" :
        return "High";
    case "Medium" :
        return "Medium";
    case "Low" :
        return "Low";
    
  }
}

function isHigherThan(p1, p2) {
  return toInt(p1) > toInt(p2);
}

var PriorityHelpers = {
  toInt: toInt,
  toString: toString$4,
  isHigherThan: isHigherThan
};

function validateRule(rule) {
  var errors = [];
  if (rule.metadata.name.length === 0) {
    errors.push("Rule name cannot be empty");
  }
  var contextRefs = getContextRefs(rule.condition);
  if (contextRefs.length === 0) {
    var match = rule.condition;
    if (typeof match !== "object") {
      match === "Always";
    } else {
      errors.push("Rule condition must reference at least one context field or be Always/Never");
    }
  }
  if (rule.actions.length === 0) {
    errors.push("Rule must have at least one action");
  }
  var validateConditionOperands = function (_cond) {
    while(true) {
      var cond = _cond;
      if (typeof cond !== "object") {
        return ;
      }
      switch (cond.TAG) {
        case "Comparison" :
            var op = cond._1;
            if (!validateOperands(op, cond._0, cond._2)) {
              errors.push("Invalid operands for operator " + toString$1(op));
              return ;
            } else {
              return ;
            }
        case "LogicalOp" :
            validateConditionOperands(cond._1);
            _cond = cond._2;
            continue ;
        case "Not" :
            _cond = cond._0;
            continue ;
        
      }
    };
  };
  validateConditionOperands(rule.condition);
  if (errors.length === 0) {
    return "Valid";
  } else {
    return {
            TAG: "Invalid",
            _0: errors
          };
  }
}

var RuleValidation = {
  validateRule: validateRule
};

function createSimpleRule(name, condition, actions) {
  return {
          metadata: {
            name: name,
            description: undefined,
            tags: [],
            enabled: true,
            createdAt: Date.now(),
            updatedAt: undefined
          },
          priority: "Medium",
          condition: condition,
          actions: actions
        };
}

function createHighPriorityRule(name, condition, actions) {
  var init = createSimpleRule(name, condition, actions);
  return {
          metadata: init.metadata,
          priority: "High",
          condition: init.condition,
          actions: init.actions
        };
}

function createDefaultRule(name, actions) {
  return createSimpleRule(name, "Always", actions);
}

var RuleFactory = {
  createSimpleRule: createSimpleRule,
  createHighPriorityRule: createHighPriorityRule,
  createDefaultRule: createDefaultRule
};

function compareByPriority(r1, r2) {
  return toInt(r2.priority) - toInt(r1.priority) | 0;
}

var conditionToString = toString$2;

var actionToString = toString$3;

var priorityToInt = toInt;

export {
  ValueHelpers ,
  CompareOpHelpers ,
  ConditionHelpers ,
  ActionHelpers ,
  PriorityHelpers ,
  RuleValidation ,
  RuleFactory ,
  createSimpleRule ,
  createHighPriorityRule ,
  createDefaultRule ,
  validateRule ,
  conditionToString ,
  actionToString ,
  priorityToInt ,
  compareByPriority ,
}
/* No side effect */
