// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as PolicyDSL from "./PolicyDSL.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Result from "rescript/lib/es6/belt_Result.js";
import * as TaskStateMachine from "../runtime/TaskStateMachine.bs.js";

function createExecutionContext(currentState, $$event, metadata, policy, param) {
  return {
          currentState: currentState,
          event: $$event,
          metadata: metadata,
          policy: policy
        };
}

function evaluateCondition(condition, context) {
  switch (condition.TAG) {
    case "StateIs" :
        var currentStateStr = TaskStateMachine.State.toString(context.currentState);
        return currentStateStr === condition._0;
    case "EventIs" :
        var currentEventStr = TaskStateMachine.$$Event.toString(context.event);
        return currentEventStr === condition._0;
    case "MetadataHas" :
        var dict = context.metadata;
        if (dict !== undefined) {
          return Js_dict.get(dict, condition._0) !== undefined;
        } else {
          return false;
        }
    case "DependencyAvailable" :
        return true;
    
  }
}

function evaluateRuleConditions(rule, context) {
  if (rule.conditions.length === 0) {
    return true;
  } else {
    return Belt_Array.every(rule.conditions, (function (condition) {
                  return evaluateCondition(condition, context);
                }));
  }
}

function evaluateRule(rule, context) {
  var conditionsMet = evaluateRuleConditions(rule, context);
  if (!conditionsMet) {
    return "RulePass";
  }
  var reason = rule.action;
  if (typeof reason !== "object") {
    return "RulePass";
  }
  if (reason.TAG === "Deny") {
    return {
            TAG: "RuleFail",
            _0: "Rule " + rule.ruleId + " denied: " + reason._0
          };
  }
  var requirement = reason._0;
  var dict = context.metadata;
  if (dict === undefined) {
    return {
            TAG: "RuleFail",
            _0: "Rule " + rule.ruleId + " requires: " + requirement
          };
  }
  var match = Js_dict.get(dict, requirement);
  if (match !== undefined) {
    return "RulePass";
  } else {
    return {
            TAG: "RuleFail",
            _0: "Rule " + rule.ruleId + " requires: " + requirement
          };
  }
}

function evaluatePolicy(policy, context) {
  var rulesEvaluated = {
    contents: 0
  };
  var finalResult = {
    contents: "RulePass"
  };
  var failureReason = {
    contents: undefined
  };
  Belt_Array.forEach(policy.rules, (function (rule) {
          var match = finalResult.contents;
          var tmp;
          tmp = typeof match !== "object" ? ({
                TAG: "Ok",
                _0: undefined
              }) : ({
                TAG: "Error",
                _0: undefined
              });
          if (!Belt_Result.isOk(tmp)) {
            return ;
          }
          rulesEvaluated.contents = rulesEvaluated.contents + 1 | 0;
          var result = evaluateRule(rule, context);
          if (typeof result !== "object") {
            return ;
          }
          if (result.TAG === "RuleFail") {
            var reason = result._0;
            finalResult.contents = {
              TAG: "RuleFail",
              _0: reason
            };
            failureReason.contents = reason;
            return ;
          }
          var reason$1 = result._0;
          finalResult.contents = {
            TAG: "RuleDefer",
            _0: reason$1
          };
          failureReason.contents = reason$1;
        }));
  return {
          policy: policy,
          rulesEvaluated: rulesEvaluated.contents,
          result: finalResult.contents,
          reason: failureReason.contents
        };
}

function execute(context) {
  var policy = context.policy;
  if (policy !== undefined) {
    return evaluatePolicy(policy, context);
  } else {
    return {
            policy: undefined,
            rulesEvaluated: 0,
            result: "RulePass",
            reason: undefined
          };
  }
}

function evaluationResultToString(result) {
  if (typeof result !== "object") {
    return "RulePass";
  } else if (result.TAG === "RuleFail") {
    return "RuleFail(" + result._0 + ")";
  } else {
    return "RuleDefer(" + result._0 + ")";
  }
}

function outcomeToString(outcome) {
  var p = outcome.policy;
  var policyStr = p !== undefined ? PolicyDSL.policyToString(p) : "None";
  var resultStr = evaluationResultToString(outcome.result);
  return "Outcome(policy=" + policyStr + ", evaluated=" + String(outcome.rulesEvaluated) + ", result=" + resultStr + ")";
}

function isPassed(result) {
  if (typeof result !== "object") {
    return true;
  } else {
    return false;
  }
}

function isFailed(result) {
  if (typeof result !== "object" || result.TAG !== "RuleFail") {
    return false;
  } else {
    return true;
  }
}

function isDeferred(result) {
  if (typeof result !== "object" || result.TAG === "RuleFail") {
    return false;
  } else {
    return true;
  }
}

function getFailureReason(result) {
  if (typeof result !== "object" || result.TAG !== "RuleFail") {
    return ;
  } else {
    return result._0;
  }
}

export {
  createExecutionContext ,
  evaluateCondition ,
  evaluateRuleConditions ,
  evaluateRule ,
  evaluatePolicy ,
  execute ,
  evaluationResultToString ,
  outcomeToString ,
  isPassed ,
  isFailed ,
  isDeferred ,
  getFailureReason ,
}
/* No side effect */
