/**
 * Template Registry
 *
 * Week 3-4 Implementation - Day 4
 * Manages Handlebars templates for scaffold generation
 */

import Handlebars from 'handlebars';

/**
 * Template Registry
 *
 * Manages template registration, compilation, and retrieval for scaffold generation.
 * Uses Handlebars for template rendering with custom helpers.
 */
export class TemplateRegistry {
  private templates: Map<string, HandlebarsTemplateDelegate> = new Map();

  constructor() {
    this.registerHelpers();
    this.registerBuiltInTemplates();
  }

  /**
   * Register custom Handlebars helpers
   */
  private registerHelpers(): void {
    // Helper: Convert object to JSON string
    Handlebars.registerHelper('json', function (context) {
      return JSON.stringify(context, null, 2);
    });

    // Helper: Join array with separator
    Handlebars.registerHelper('join', function (array: any[], separator: string) {
      if (!Array.isArray(array)) return '';
      return array.join(separator);
    });

    // Helper: Increment number (for 1-indexed lists)
    Handlebars.registerHelper('inc', function (value: number) {
      return value + 1;
    });

    // Helper: Format date
    Handlebars.registerHelper('date', function (format?: string) {
      const now = new Date();
      if (format === 'iso') {
        return now.toISOString();
      }
      return now.toLocaleDateString();
    });

    // Helper: Conditional unless (opposite of if)
    Handlebars.registerHelper('unless', function (this: any, conditional: any, options: any) {
      if (!conditional) {
        return options.fn(this);
      }
      return options.inverse(this);
    });
  }

  /**
   * Register built-in templates
   */
  private registerBuiltInTemplates(): void {
    // Workflow YAML template
    this.register('workflow.yaml', `# {{workflow.name}}
# Version: {{workflow.version}}
# Generated by {{generator}} on {{timestamp}}
{{#if workflow.description}}
# {{workflow.description}}
{{/if}}

name: "{{workflow.name}}"
version: "{{workflow.version}}"
{{#if workflow.description}}
description: "{{workflow.description}}"
{{/if}}

steps:
{{#each workflow.steps}}
  - id: "{{this.id}}"
    name: "{{this.name}}"
    action: "{{this.action}}"
    config: {{json this.config}}
    {{#if this.dependsOn}}
    dependsOn: {{json this.dependsOn}}
    {{/if}}
    {{#if this.duration}}
    duration: {{this.duration}}
    {{/if}}
    {{#if this.timeout}}
    timeout: {{this.timeout}}
    {{/if}}
    {{#if this.retry}}
    retry: {{json this.retry}}
    {{/if}}
{{/each}}
`);

    // Config JSON template
    this.register('config.json', `{
  "workflow": {
    "name": "{{workflow.name}}",
    "version": "{{workflow.version}}",
    "timeout": 600000,
    "retryPolicy": {
      "maxRetries": 3,
      "backoffMultiplier": 2,
      "initialDelay": 1000
    }
  },
  "providers": {
    "claude": {
      "model": "claude-3-5-sonnet-20241022",
      "maxTokens": 4096,
      "temperature": 0.7
    },
    "gemini": {
      "model": "gemini-2.0-flash-exp",
      "maxTokens": 8192,
      "temperature": 0.7
    },
    "openai": {
      "model": "gpt-4o",
      "maxTokens": 4096,
      "temperature": 0.7
    }
  },
  "outputs": {
    "directory": "./outputs",
    "format": "json",
    "includeTimestamp": true
  },
  "logging": {
    "level": "info",
    "directory": "./logs",
    "maxFiles": 10,
    "maxSize": "10m"
  }
}
`);

    // Run script template
    this.register('run.sh', `#!/bin/bash
# {{workflow.name}} - Execution Script
# Generated by {{generator}}

set -e  # Exit on error
set -u  # Error on undefined variables

# Colors
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Default config
CONFIG_FILE="\${PROJECT_DIR}/configs/default.json"

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    -c|--config)
      CONFIG_FILE="$2"
      shift 2
      ;;
    -v|--verbose)
      VERBOSE=true
      shift
      ;;
    -h|--help)
      echo "Usage: $0 [OPTIONS]"
      echo "Options:"
      echo "  -c, --config <file>   Config file (default: configs/default.json)"
      echo "  -v, --verbose         Verbose output"
      echo "  -h, --help            Show this help"
      exit 0
      ;;
    *)
      echo -e "\${RED}Unknown option: $1\${NC}"
      exit 1
      ;;
  esac
done

# Validate config exists
if [ ! -f "$CONFIG_FILE" ]; then
  echo -e "\${RED}Config file not found: $CONFIG_FILE\${NC}"
  exit 1
fi

# Print header
echo -e "\${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\${NC}"
echo -e "\${BLUE}  {{workflow.name}}\${NC}"
echo -e "\${BLUE}  Version: {{workflow.version}}\${NC}"
echo -e "\${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\${NC}"
echo ""

# Check dependencies
echo -e "\${YELLOW}Checking dependencies...\${NC}"
if ! command -v ax &> /dev/null; then
  echo -e "\${RED}AutomatosX CLI not found. Install: npm install -g automatosx\${NC}"
  exit 1
fi
echo -e "\${GREEN}✓ Dependencies OK\${NC}"
echo ""

# Run workflow
echo -e "\${YELLOW}Running workflow...\${NC}"
START_TIME=$(date +%s)

if [ "\${VERBOSE:-false}" = true ]; then
  ax workflow run "\${PROJECT_DIR}/workflows/main.yaml" \\
    --config "$CONFIG_FILE" \\
    --verbose
else
  ax workflow run "\${PROJECT_DIR}/workflows/main.yaml" \\
    --config "$CONFIG_FILE"
fi

EXIT_CODE=$?
END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))

# Print summary
echo ""
echo -e "\${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\${NC}"
if [ $EXIT_CODE -eq 0 ]; then
  echo -e "\${GREEN}✅ Workflow completed successfully\${NC}"
else
  echo -e "\${RED}❌ Workflow failed with exit code $EXIT_CODE\${NC}"
fi
echo -e "\${BLUE}  Duration: \${DURATION}s\${NC}"
echo -e "\${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\${NC}"

exit $EXIT_CODE
`);

    // README template
    this.register('README.md', `# {{workflow.name}}

{{#if workflow.description}}
{{workflow.description}}
{{/if}}

**Version:** {{workflow.version}}
**Generated:** {{timestamp}}

---

## 📋 Overview

This project contains an AutomatosX workflow with {{workflow.stepCount}} steps.

### Workflow Steps

{{#each workflow.steps}}
{{inc @index}}. **{{this.name}}** (\`{{this.id}}\`)
   - Action: \`{{this.action}}\`
   {{#if this.dependsOn}}
   - Dependencies: {{join this.dependsOn ", "}}
   {{/if}}
{{/each}}

---

## 🚀 Quick Start

### Prerequisites

- Node.js v18+
- AutomatosX CLI v8.0.0+

\`\`\`bash
npm install -g automatosx
\`\`\`

### Installation

1. Clone or download this project
2. Review configuration in \`configs/default.json\`
3. Update environment variables (if needed)

### Running the Workflow

**Basic execution:**
\`\`\`bash
./scripts/run.sh
\`\`\`

**With custom config:**
\`\`\`bash
./scripts/run.sh --config configs/production.json
\`\`\`

**Verbose mode:**
\`\`\`bash
./scripts/run.sh --verbose
\`\`\`

---

## ⚙️ Configuration

### Default Config (\`configs/default.json\`)

The default configuration includes:
- Provider settings (Claude, Gemini, OpenAI)
- Retry policies
- Output settings
- Logging configuration

### Environment Variables

Create a \`.env\` file with:
\`\`\`bash
# API Keys
ANTHROPIC_API_KEY=your_key_here
GOOGLE_API_KEY=your_key_here
OPENAI_API_KEY=your_key_here

# Optional
LOG_LEVEL=info
OUTPUT_DIR=./outputs
\`\`\`

---

## 📁 Project Structure

\`\`\`
.
├── workflows/           # Workflow definitions
│   └── main.yaml
├── configs/            # Configuration files
│   └── default.json
├── scripts/            # Execution scripts
│   ├── run.sh
│   ├── validate.sh
│   └── cleanup.sh
├── docs/               # Documentation
{{#if options.includeTests}}
├── tests/              # Test suites
│   ├── unit/
│   └── integration/
{{/if}}
{{#if options.includeCI}}
├── .github/            # CI/CD workflows
│   └── workflows/
│       └── ci.yml
{{/if}}
├── logs/               # Execution logs
├── outputs/            # Workflow outputs
└── README.md           # This file
\`\`\`

---

## 🧪 Testing

{{#if options.includeTests}}
Run tests:
\`\`\`bash
npm test
\`\`\`
{{else}}
Tests not included. Add \`--include-tests\` when scaffolding.
{{/if}}

---

## 🔧 Maintenance

### Validate Workflow

\`\`\`bash
./scripts/validate.sh
\`\`\`

### Clean Up

\`\`\`bash
./scripts/cleanup.sh
\`\`\`

### View Logs

\`\`\`bash
tail -f logs/latest.log
\`\`\`

---

## 📄 License

This workflow was generated by AutomatosX v8.0.0.

---

**Generated by AutomatosX Scaffold Generator**
**Date:** {{timestamp}}
`);

    // Validate script
    this.register('validate.sh', `#!/bin/bash
# {{workflow.name}} - Validation Script
# Generated by {{generator}}

set -e

# Colors
GREEN='\\033[0;32m'
RED='\\033[0;31m'
NC='\\033[0m'

SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

echo "🔍 Validating workflow..."

# Check if ax command exists
if ! command -v ax &> /dev/null; then
  echo -e "\${RED}❌ AutomatosX CLI not found\${NC}"
  exit 1
fi

# Validate workflow YAML
ax workflow validate "\${PROJECT_DIR}/workflows/main.yaml"

if [ $? -eq 0 ]; then
  echo -e "\${GREEN}✅ Workflow is valid\${NC}"
else
  echo -e "\${RED}❌ Workflow validation failed\${NC}"
  exit 1
fi
`);

    // Cleanup script
    this.register('cleanup.sh', `#!/bin/bash
# {{workflow.name}} - Cleanup Script
# Generated by {{generator}}

set -e

# Colors
YELLOW='\\033[1;33m'
GREEN='\\033[0;32m'
NC='\\033[0m'

SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

echo -e "\${YELLOW}🧹 Cleaning up...\${NC}"

# Remove logs
if [ -d "\${PROJECT_DIR}/logs" ]; then
  rm -rf "\${PROJECT_DIR}/logs"/*
  echo "  ✓ Cleaned logs/"
fi

# Remove outputs
if [ -d "\${PROJECT_DIR}/outputs" ]; then
  rm -rf "\${PROJECT_DIR}/outputs"/*
  echo "  ✓ Cleaned outputs/"
fi

echo -e "\${GREEN}✅ Cleanup complete\${NC}"
`);

    // .gitignore
    this.register('.gitignore', `# Logs
logs/
*.log

# Outputs
outputs/

# Environment
.env
.env.local

# Dependencies
node_modules/

# OS files
.DS_Store
Thumbs.db

# IDE
.vscode/
.idea/
*.swp
*.swo
`);

    // CI/CD template (GitHub Actions)
    this.register('ci.yml', `name: {{workflow.name}} CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install AutomatosX CLI
        run: npm install -g automatosx

      - name: Validate Workflow
        run: ./scripts/validate.sh

  test:
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
        {{#unless options.includeTests}}
        # Tests not included in scaffold
        if: false
        {{/unless}}

  run:
    runs-on: ubuntu-latest
    needs: [validate, test]
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install AutomatosX CLI
        run: npm install -g automatosx

      - name: Run Workflow
        env:
          ANTHROPIC_API_KEY: \${{ secrets.ANTHROPIC_API_KEY }}
          GOOGLE_API_KEY: \${{ secrets.GOOGLE_API_KEY }}
          OPENAI_API_KEY: \${{ secrets.OPENAI_API_KEY }}
        run: ./scripts/run.sh
`);
  }

  /**
   * Register a template
   */
  register(name: string, template: string | HandlebarsTemplateDelegate): void {
    if (typeof template === 'string') {
      this.templates.set(name, Handlebars.compile(template));
    } else {
      this.templates.set(name, template);
    }
  }

  /**
   * Get a compiled template
   */
  getTemplate(name: string): HandlebarsTemplateDelegate {
    const template = this.templates.get(name);
    if (!template) {
      throw new Error(`Template not found: ${name}`);
    }
    return template;
  }

  /**
   * Check if template exists
   */
  hasTemplate(name: string): boolean {
    return this.templates.has(name);
  }

  /**
   * List all registered templates
   */
  listTemplates(): string[] {
    return Array.from(this.templates.keys());
  }
}
