/**
 * Workflow Fixture
 * Generated by AutomatosX v8.0.0
 */

export const workflowFixture = {
  "name": "Test Workflow",
  "version": "1.0.0",
  "description": "A test workflow",
  "steps": [
    {
      "id": "step-1",
      "name": "First Step",
      "agent": "backend",
      "action": "test-action",
      "config": {}
    },
    {
      "id": "step-2",
      "name": "Second Step",
      "agent": "security",
      "action": "test-action",
      "config": {},
      "dependsOn": [
        "step-1"
      ]
    }
  ],
  "config": {}
};

export const expectedWorkflowOutput = {
  success: true,
  completedSteps: 2,
  failedSteps: 0,
  duration: 0, // Will be set by actual execution
  cost: 0, // Will be calculated
  output: {},
};

export const workflowMetadata = {
  totalSteps: 2,
  estimatedDuration: 10000,
  estimatedCost: 0.02,
  hasRetryConfig: false,
  hasDependencies: true,
};
