// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as TaskPlanner from "./TaskPlanner.bs.js";
import * as StateMachine from "../state/StateMachine.bs.js";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";

function getCurrentTime() {
  return Date.now();
}

function executionStatusToString(status) {
  switch (status) {
    case "Pending" :
        return "pending";
    case "Running" :
        return "running";
    case "Paused" :
        return "paused";
    case "Completed" :
        return "completed";
    case "Failed" :
        return "failed";
    case "Cancelled" :
        return "cancelled";
    case "TimedOut" :
        return "timedout";
    
  }
}

function stringToExecutionStatus(str) {
  switch (str) {
    case "cancelled" :
        return "Cancelled";
    case "completed" :
        return "Completed";
    case "failed" :
        return "Failed";
    case "paused" :
        return "Paused";
    case "pending" :
        return "Pending";
    case "running" :
        return "Running";
    case "timedout" :
        return "TimedOut";
    default:
      return ;
  }
}

function stateToExecutionStatus(state) {
  if (typeof state !== "object") {
    return "Pending";
  }
  switch (state.TAG) {
    case "Running" :
        return "Running";
    case "Paused" :
        return "Paused";
    case "Completed" :
        return "Completed";
    case "Failed" :
        return "Failed";
    
  }
}

function createWorkflowTransitions() {
  return [
          {
            from: "Idle",
            event: "Start",
            to: {
              TAG: "Running",
              _0: {
                instanceId: "",
                workflowId: "",
                currentTasks: [],
                completedTasks: [],
                failedTasks: [],
                taskExecutions: undefined
              }
            },
            guard: undefined,
            action: undefined
          },
          {
            from: {
              TAG: "Running",
              _0: {
                instanceId: "",
                workflowId: "",
                currentTasks: [],
                completedTasks: [],
                failedTasks: [],
                taskExecutions: undefined
              }
            },
            event: "Pause",
            to: {
              TAG: "Paused",
              _0: {
                instanceId: "",
                workflowId: "",
                currentTasks: [],
                completedTasks: [],
                failedTasks: [],
                taskExecutions: undefined
              }
            },
            guard: undefined,
            action: undefined
          },
          {
            from: {
              TAG: "Paused",
              _0: {
                instanceId: "",
                workflowId: "",
                currentTasks: [],
                completedTasks: [],
                failedTasks: [],
                taskExecutions: undefined
              }
            },
            event: "Resume",
            to: {
              TAG: "Running",
              _0: {
                instanceId: "",
                workflowId: "",
                currentTasks: [],
                completedTasks: [],
                failedTasks: [],
                taskExecutions: undefined
              }
            },
            guard: undefined,
            action: undefined
          },
          {
            from: {
              TAG: "Running",
              _0: {
                instanceId: "",
                workflowId: "",
                currentTasks: [],
                completedTasks: [],
                failedTasks: [],
                taskExecutions: undefined
              }
            },
            event: "Complete",
            to: {
              TAG: "Completed",
              _0: {
                instanceId: "",
                workflowId: "",
                currentTasks: [],
                completedTasks: [],
                failedTasks: [],
                taskExecutions: undefined
              }
            },
            guard: undefined,
            action: undefined
          },
          {
            from: {
              TAG: "Running",
              _0: {
                instanceId: "",
                workflowId: "",
                currentTasks: [],
                completedTasks: [],
                failedTasks: [],
                taskExecutions: undefined
              }
            },
            event: "Fail",
            to: {
              TAG: "Failed",
              _0: "Workflow failed"
            },
            guard: undefined,
            action: undefined
          },
          {
            from: "Idle",
            event: "Cancel",
            to: {
              TAG: "Completed",
              _0: {
                instanceId: "",
                workflowId: "",
                currentTasks: [],
                completedTasks: [],
                failedTasks: [],
                taskExecutions: undefined
              }
            },
            guard: undefined,
            action: undefined
          },
          {
            from: {
              TAG: "Running",
              _0: {
                instanceId: "",
                workflowId: "",
                currentTasks: [],
                completedTasks: [],
                failedTasks: [],
                taskExecutions: undefined
              }
            },
            event: "Cancel",
            to: {
              TAG: "Completed",
              _0: {
                instanceId: "",
                workflowId: "",
                currentTasks: [],
                completedTasks: [],
                failedTasks: [],
                taskExecutions: undefined
              }
            },
            guard: undefined,
            action: undefined
          },
          {
            from: {
              TAG: "Paused",
              _0: {
                instanceId: "",
                workflowId: "",
                currentTasks: [],
                completedTasks: [],
                failedTasks: [],
                taskExecutions: undefined
              }
            },
            event: "Cancel",
            to: {
              TAG: "Completed",
              _0: {
                instanceId: "",
                workflowId: "",
                currentTasks: [],
                completedTasks: [],
                failedTasks: [],
                taskExecutions: undefined
              }
            },
            guard: undefined,
            action: undefined
          }
        ];
}

function createWorkflowDefinition(id, name, description, tasks, maxRetries, timeout, allowParallel) {
  return {
          id: id,
          name: name,
          description: description,
          tasks: tasks,
          maxRetries: maxRetries,
          timeout: timeout,
          allowParallel: allowParallel
        };
}

function createWorkflowInstance(definition) {
  var planResult = TaskPlanner.plan(definition.tasks);
  if (planResult.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: planResult._0
          };
  }
  var transitions = createWorkflowTransitions();
  var stateMachine = StateMachine.create("Idle", transitions, undefined, undefined);
  var instanceId = "instance-" + definition.id + "-" + String(Date.now());
  var instance_workflowId = definition.id;
  var instance_plan = planResult._0;
  var instance_currentTasks = [];
  var instance_completedTasks = [];
  var instance_failedTasks = [];
  var instance_createdAt = Date.now();
  var instance = {
    id: instanceId,
    workflowId: instance_workflowId,
    definition: definition,
    plan: instance_plan,
    status: "Pending",
    currentTasks: instance_currentTasks,
    completedTasks: instance_completedTasks,
    failedTasks: instance_failedTasks,
    taskExecutions: undefined,
    stateMachine: stateMachine,
    createdAt: instance_createdAt,
    startedAt: undefined,
    completedAt: undefined,
    error: undefined
  };
  return {
          TAG: "Ok",
          _0: instance
        };
}

function createTaskExecution(taskId) {
  return {
          taskId: taskId,
          status: "Pending",
          startTime: undefined,
          endTime: undefined,
          attempts: 0,
          error: undefined
        };
}

function startTaskExecution(execution) {
  return {
          taskId: execution.taskId,
          status: "Running",
          startTime: Date.now(),
          endTime: execution.endTime,
          attempts: execution.attempts + 1 | 0,
          error: execution.error
        };
}

function completeTaskExecution(execution) {
  return {
          taskId: execution.taskId,
          status: "Completed",
          startTime: execution.startTime,
          endTime: Date.now(),
          attempts: execution.attempts,
          error: execution.error
        };
}

function failTaskExecution(execution, error) {
  return {
          taskId: execution.taskId,
          status: "Failed",
          startTime: execution.startTime,
          endTime: Date.now(),
          attempts: execution.attempts,
          error: error
        };
}

async function startWorkflow(instance) {
  var $$event = StateMachine.createEvent("start", "Start", undefined, undefined);
  var transitionResult = await StateMachine.transition(instance.stateMachine, $$event);
  if (transitionResult.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: transitionResult._0
          };
  }
  var firstTasks = instance.plan.parallelGroups.length > 0 ? Belt_Option.getWithDefault(Belt_Array.get(instance.plan.parallelGroups, 0), []) : [];
  var taskExecutions = Belt_Array.reduce(instance.plan.tasks, undefined, (function (acc, task) {
          var execution = createTaskExecution(task.id);
          return Belt_MapString.set(acc, task.id, execution);
        }));
  var updatedInstance_id = instance.id;
  var updatedInstance_workflowId = instance.workflowId;
  var updatedInstance_definition = instance.definition;
  var updatedInstance_plan = instance.plan;
  var updatedInstance_completedTasks = instance.completedTasks;
  var updatedInstance_failedTasks = instance.failedTasks;
  var updatedInstance_stateMachine = instance.stateMachine;
  var updatedInstance_createdAt = instance.createdAt;
  var updatedInstance_startedAt = Date.now();
  var updatedInstance_completedAt = instance.completedAt;
  var updatedInstance_error = instance.error;
  var updatedInstance = {
    id: updatedInstance_id,
    workflowId: updatedInstance_workflowId,
    definition: updatedInstance_definition,
    plan: updatedInstance_plan,
    status: "Running",
    currentTasks: firstTasks,
    completedTasks: updatedInstance_completedTasks,
    failedTasks: updatedInstance_failedTasks,
    taskExecutions: taskExecutions,
    stateMachine: updatedInstance_stateMachine,
    createdAt: updatedInstance_createdAt,
    startedAt: updatedInstance_startedAt,
    completedAt: updatedInstance_completedAt,
    error: updatedInstance_error
  };
  return {
          TAG: "Ok",
          _0: updatedInstance
        };
}

async function pauseWorkflow(instance) {
  var $$event = StateMachine.createEvent("pause", "Pause", undefined, undefined);
  var transitionResult = await StateMachine.transition(instance.stateMachine, $$event);
  if (transitionResult.TAG === "Ok") {
    return {
            TAG: "Ok",
            _0: {
              id: instance.id,
              workflowId: instance.workflowId,
              definition: instance.definition,
              plan: instance.plan,
              status: "Paused",
              currentTasks: instance.currentTasks,
              completedTasks: instance.completedTasks,
              failedTasks: instance.failedTasks,
              taskExecutions: instance.taskExecutions,
              stateMachine: instance.stateMachine,
              createdAt: instance.createdAt,
              startedAt: instance.startedAt,
              completedAt: instance.completedAt,
              error: instance.error
            }
          };
  } else {
    return {
            TAG: "Error",
            _0: transitionResult._0
          };
  }
}

async function resumeWorkflow(instance) {
  var $$event = StateMachine.createEvent("resume", "Resume", undefined, undefined);
  var transitionResult = await StateMachine.transition(instance.stateMachine, $$event);
  if (transitionResult.TAG === "Ok") {
    return {
            TAG: "Ok",
            _0: {
              id: instance.id,
              workflowId: instance.workflowId,
              definition: instance.definition,
              plan: instance.plan,
              status: "Running",
              currentTasks: instance.currentTasks,
              completedTasks: instance.completedTasks,
              failedTasks: instance.failedTasks,
              taskExecutions: instance.taskExecutions,
              stateMachine: instance.stateMachine,
              createdAt: instance.createdAt,
              startedAt: instance.startedAt,
              completedAt: instance.completedAt,
              error: instance.error
            }
          };
  } else {
    return {
            TAG: "Error",
            _0: transitionResult._0
          };
  }
}

async function cancelWorkflow(instance) {
  var $$event = StateMachine.createEvent("cancel", "Cancel", undefined, undefined);
  var transitionResult = await StateMachine.transition(instance.stateMachine, $$event);
  if (transitionResult.TAG === "Ok") {
    return {
            TAG: "Ok",
            _0: {
              id: instance.id,
              workflowId: instance.workflowId,
              definition: instance.definition,
              plan: instance.plan,
              status: "Cancelled",
              currentTasks: instance.currentTasks,
              completedTasks: instance.completedTasks,
              failedTasks: instance.failedTasks,
              taskExecutions: instance.taskExecutions,
              stateMachine: instance.stateMachine,
              createdAt: instance.createdAt,
              startedAt: instance.startedAt,
              completedAt: Date.now(),
              error: instance.error
            }
          };
  } else {
    return {
            TAG: "Error",
            _0: transitionResult._0
          };
  }
}

function getNextTasks(plan, completedTasksList, completedTaskId) {
  var currentGroupIndex = Belt_Array.reduceWithIndex(plan.parallelGroups, undefined, (function (acc, group, index) {
          if (acc !== undefined) {
            return acc;
          } else if (Belt_Array.some(group, (function (id) {
                    return id === completedTaskId;
                  }))) {
            return index;
          } else {
            return ;
          }
        }));
  if (currentGroupIndex === undefined) {
    return [];
  }
  var currentGroup = Belt_Option.getWithDefault(Belt_Array.get(plan.parallelGroups, currentGroupIndex), []);
  var allCompleted = Belt_Array.every(currentGroup, (function (taskId) {
          return Belt_Array.some(completedTasksList, (function (id) {
                        return id === taskId;
                      }));
        }));
  if (allCompleted) {
    return Belt_Option.getWithDefault(Belt_Array.get(plan.parallelGroups, currentGroupIndex + 1 | 0), []);
  } else {
    return [];
  }
}

async function completeTask(instance, taskId) {
  var executionOpt = Belt_MapString.get(instance.taskExecutions, taskId);
  if (executionOpt === undefined) {
    return {
            TAG: "Error",
            _0: "Task execution not found: " + taskId
          };
  }
  var completedExecution = completeTaskExecution(executionOpt);
  var updatedExecutions = Belt_MapString.set(instance.taskExecutions, taskId, completedExecution);
  var completedTasks = instance.completedTasks.concat([taskId]);
  var currentTasks = Belt_Array.keep(instance.currentTasks, (function (id) {
          return id !== taskId;
        }));
  var nextTasks = getNextTasks(instance.plan, completedTasks, taskId);
  var newCurrentTasks = currentTasks.concat(nextTasks);
  var updatedExecutions2 = Belt_Array.reduce(nextTasks, updatedExecutions, (function (acc, nextId) {
          var execOpt = Belt_MapString.get(acc, nextId);
          if (execOpt === undefined) {
            return acc;
          }
          var startedExec = startTaskExecution(execOpt);
          return Belt_MapString.set(acc, nextId, startedExec);
        }));
  var isComplete = completedTasks.length === instance.plan.tasks.length;
  if (!isComplete) {
    return {
            TAG: "Ok",
            _0: {
              id: instance.id,
              workflowId: instance.workflowId,
              definition: instance.definition,
              plan: instance.plan,
              status: instance.status,
              currentTasks: newCurrentTasks,
              completedTasks: completedTasks,
              failedTasks: instance.failedTasks,
              taskExecutions: updatedExecutions2,
              stateMachine: instance.stateMachine,
              createdAt: instance.createdAt,
              startedAt: instance.startedAt,
              completedAt: instance.completedAt,
              error: instance.error
            }
          };
  }
  var $$event = StateMachine.createEvent("complete", "Complete", undefined, undefined);
  var transitionResult = await StateMachine.transition(instance.stateMachine, $$event);
  if (transitionResult.TAG === "Ok") {
    return {
            TAG: "Ok",
            _0: {
              id: instance.id,
              workflowId: instance.workflowId,
              definition: instance.definition,
              plan: instance.plan,
              status: "Completed",
              currentTasks: newCurrentTasks,
              completedTasks: completedTasks,
              failedTasks: instance.failedTasks,
              taskExecutions: updatedExecutions2,
              stateMachine: instance.stateMachine,
              createdAt: instance.createdAt,
              startedAt: instance.startedAt,
              completedAt: Date.now(),
              error: instance.error
            }
          };
  } else {
    return {
            TAG: "Error",
            _0: transitionResult._0
          };
  }
}

async function failTask(instance, taskId, error) {
  var executionOpt = Belt_MapString.get(instance.taskExecutions, taskId);
  if (executionOpt === undefined) {
    return {
            TAG: "Error",
            _0: "Task execution not found: " + taskId
          };
  }
  var canRetry = executionOpt.attempts < instance.definition.maxRetries;
  if (canRetry) {
    var retriedExecution = startTaskExecution(executionOpt);
    var updatedExecutions = Belt_MapString.set(instance.taskExecutions, taskId, retriedExecution);
    return {
            TAG: "Ok",
            _0: {
              id: instance.id,
              workflowId: instance.workflowId,
              definition: instance.definition,
              plan: instance.plan,
              status: instance.status,
              currentTasks: instance.currentTasks,
              completedTasks: instance.completedTasks,
              failedTasks: instance.failedTasks,
              taskExecutions: updatedExecutions,
              stateMachine: instance.stateMachine,
              createdAt: instance.createdAt,
              startedAt: instance.startedAt,
              completedAt: instance.completedAt,
              error: instance.error
            }
          };
  }
  var failedExecution = failTaskExecution(executionOpt, error);
  var updatedExecutions$1 = Belt_MapString.set(instance.taskExecutions, taskId, failedExecution);
  var failedTasks = instance.failedTasks.concat([taskId]);
  var currentTasks = Belt_Array.keep(instance.currentTasks, (function (id) {
          return id !== taskId;
        }));
  var $$event = StateMachine.createEvent("fail", "Fail", undefined, undefined);
  var transitionResult = await StateMachine.transition(instance.stateMachine, $$event);
  if (transitionResult.TAG === "Ok") {
    return {
            TAG: "Ok",
            _0: {
              id: instance.id,
              workflowId: instance.workflowId,
              definition: instance.definition,
              plan: instance.plan,
              status: "Failed",
              currentTasks: currentTasks,
              completedTasks: instance.completedTasks,
              failedTasks: failedTasks,
              taskExecutions: updatedExecutions$1,
              stateMachine: instance.stateMachine,
              createdAt: instance.createdAt,
              startedAt: instance.startedAt,
              completedAt: Date.now(),
              error: "Task failed: " + taskId + " - " + error
            }
          };
  } else {
    return {
            TAG: "Error",
            _0: transitionResult._0
          };
  }
}

function getWorkflowMetrics(instance) {
  var totalTasks = instance.plan.tasks.length;
  var completedTasks = instance.completedTasks.length;
  var failedTasks = instance.failedTasks.length;
  var runningTasks = instance.currentTasks.length;
  var successRate = totalTasks > 0 ? completedTasks / totalTasks : 0.0;
  var match = instance.status;
  var estimatedTimeRemaining;
  if (match === "Running") {
    var remainingTasks = totalTasks - completedTasks | 0;
    estimatedTimeRemaining = remainingTasks > 0 ? instance.plan.estimatedTotalTime : 0;
  } else {
    estimatedTimeRemaining = undefined;
  }
  var match$1 = instance.startedAt;
  var match$2 = instance.completedAt;
  var actualDuration = match$1 !== undefined ? (
      match$2 !== undefined ? match$2 - match$1 | 0 : Date.now() - match$1 | 0
    ) : undefined;
  return {
          totalTasks: totalTasks,
          completedTasks: completedTasks,
          failedTasks: failedTasks,
          runningTasks: runningTasks,
          successRate: successRate,
          estimatedTimeRemaining: estimatedTimeRemaining,
          actualDuration: actualDuration
        };
}

function isWorkflowComplete(instance) {
  var match = instance.status;
  switch (match) {
    case "Pending" :
    case "Running" :
    case "Paused" :
        return false;
    default:
      return true;
  }
}

function isWorkflowRunning(instance) {
  var match = instance.status;
  if (match === "Running") {
    return true;
  } else {
    return false;
  }
}

function getTaskStatus(instance, taskId) {
  return Belt_Option.map(Belt_MapString.get(instance.taskExecutions, taskId), (function (exec) {
                return exec.status;
              }));
}

function getRunningTasks(instance) {
  return instance.currentTasks;
}

function getCompletedTasks(instance) {
  return instance.completedTasks;
}

function getFailedTasks(instance) {
  return instance.failedTasks;
}

function getWorkflowProgress(instance) {
  var total = instance.plan.tasks.length;
  if (total === 0) {
    return 1.0;
  } else {
    return instance.completedTasks.length / total;
  }
}

export {
  getCurrentTime ,
  executionStatusToString ,
  stringToExecutionStatus ,
  stateToExecutionStatus ,
  createWorkflowTransitions ,
  createWorkflowDefinition ,
  createWorkflowInstance ,
  createTaskExecution ,
  startTaskExecution ,
  completeTaskExecution ,
  failTaskExecution ,
  startWorkflow ,
  pauseWorkflow ,
  resumeWorkflow ,
  cancelWorkflow ,
  getNextTasks ,
  completeTask ,
  failTask ,
  getWorkflowMetrics ,
  isWorkflowComplete ,
  isWorkflowRunning ,
  getTaskStatus ,
  getRunningTasks ,
  getCompletedTasks ,
  getFailedTasks ,
  getWorkflowProgress ,
}
/* No side effect */
