// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function toString(state) {
  switch (state) {
    case "Idle" :
        return "idle";
    case "Parsing" :
        return "parsing";
    case "Validating" :
        return "validating";
    case "Executing" :
        return "executing";
    case "Paused" :
        return "paused";
    case "Completed" :
        return "completed";
    case "Failed" :
        return "failed";
    case "Cancelled" :
        return "cancelled";
    
  }
}

function fromString(str) {
  switch (str) {
    case "cancelled" :
        return "Cancelled";
    case "completed" :
        return "Completed";
    case "executing" :
        return "Executing";
    case "failed" :
        return "Failed";
    case "idle" :
        return "Idle";
    case "parsing" :
        return "Parsing";
    case "paused" :
        return "Paused";
    case "validating" :
        return "Validating";
    default:
      return ;
  }
}

function isTerminal(state) {
  switch (state) {
    case "Completed" :
    case "Failed" :
    case "Cancelled" :
        return true;
    default:
      return false;
  }
}

function isActive(state) {
  switch (state) {
    case "Parsing" :
    case "Validating" :
    case "Executing" :
        return true;
    default:
      return false;
  }
}

var State = {
  toString: toString,
  fromString: fromString,
  isTerminal: isTerminal,
  isActive: isActive
};

function toString$1($$event) {
  if (typeof $$event === "object") {
    return "fail";
  }
  switch ($$event) {
    case "Start" :
        return "start";
    case "Parse" :
        return "parse";
    case "Validate" :
        return "validate";
    case "Execute" :
        return "execute";
    case "Pause" :
        return "pause";
    case "Resume" :
        return "resume";
    case "Complete" :
        return "complete";
    case "Cancel" :
        return "cancel";
    
  }
}

function getError($$event) {
  if (typeof $$event !== "object") {
    return ;
  } else {
    return $$event.error;
  }
}

var $$Event = {
  toString: toString$1,
  getError: getError
};

function make(id) {
  return {
          id: id,
          status: "Pending",
          startedAt: undefined,
          completedAt: undefined,
          error: undefined,
          result: undefined
        };
}

function statusToString(status) {
  switch (status) {
    case "Pending" :
        return "pending";
    case "Running" :
        return "running";
    case "Completed" :
        return "completed";
    case "Failed" :
        return "failed";
    case "Skipped" :
        return "skipped";
    
  }
}

function statusFromString(str) {
  switch (str) {
    case "completed" :
        return "Completed";
    case "failed" :
        return "Failed";
    case "pending" :
        return "Pending";
    case "running" :
        return "Running";
    case "skipped" :
        return "Skipped";
    default:
      return ;
  }
}

function start(step) {
  return {
          id: step.id,
          status: "Running",
          startedAt: Date.now(),
          completedAt: step.completedAt,
          error: step.error,
          result: step.result
        };
}

function complete(step, result) {
  return {
          id: step.id,
          status: "Completed",
          startedAt: step.startedAt,
          completedAt: Date.now(),
          error: step.error,
          result: result
        };
}

function fail(step, error) {
  return {
          id: step.id,
          status: "Failed",
          startedAt: step.startedAt,
          completedAt: Date.now(),
          error: error,
          result: step.result
        };
}

function skip(step) {
  return {
          id: step.id,
          status: "Skipped",
          startedAt: step.startedAt,
          completedAt: Date.now(),
          error: step.error,
          result: step.result
        };
}

var StepState = {
  make: make,
  statusToString: statusToString,
  statusFromString: statusFromString,
  start: start,
  complete: complete,
  fail: fail,
  skip: skip
};

function make$1(workflowId, workflowName, steps) {
  return {
          workflowId: workflowId,
          workflowName: workflowName,
          variables: {},
          steps: Belt_Array.map(steps, make),
          currentStepIndex: 0,
          history: ["Idle"],
          error: undefined,
          startedAt: undefined,
          completedAt: undefined,
          pausedAt: undefined
        };
}

function setVariable(ctx, key, value) {
  var variables = Js_dict.fromArray(Js_dict.entries(ctx.variables));
  variables[key] = value;
  return {
          workflowId: ctx.workflowId,
          workflowName: ctx.workflowName,
          variables: variables,
          steps: ctx.steps,
          currentStepIndex: ctx.currentStepIndex,
          history: ctx.history,
          error: ctx.error,
          startedAt: ctx.startedAt,
          completedAt: ctx.completedAt,
          pausedAt: ctx.pausedAt
        };
}

function getVariable(ctx, key) {
  return Js_dict.get(ctx.variables, key);
}

function updateStep(ctx, stepId, updateFn) {
  var steps = Belt_Array.map(ctx.steps, (function (step) {
          if (step.id === stepId) {
            return updateFn(step);
          } else {
            return step;
          }
        }));
  return {
          workflowId: ctx.workflowId,
          workflowName: ctx.workflowName,
          variables: ctx.variables,
          steps: steps,
          currentStepIndex: ctx.currentStepIndex,
          history: ctx.history,
          error: ctx.error,
          startedAt: ctx.startedAt,
          completedAt: ctx.completedAt,
          pausedAt: ctx.pausedAt
        };
}

function getCurrentStep(ctx) {
  return Belt_Array.get(ctx.steps, ctx.currentStepIndex);
}

function advanceStep(ctx) {
  return {
          workflowId: ctx.workflowId,
          workflowName: ctx.workflowName,
          variables: ctx.variables,
          steps: ctx.steps,
          currentStepIndex: ctx.currentStepIndex + 1 | 0,
          history: ctx.history,
          error: ctx.error,
          startedAt: ctx.startedAt,
          completedAt: ctx.completedAt,
          pausedAt: ctx.pausedAt
        };
}

function setError(ctx, error) {
  return {
          workflowId: ctx.workflowId,
          workflowName: ctx.workflowName,
          variables: ctx.variables,
          steps: ctx.steps,
          currentStepIndex: ctx.currentStepIndex,
          history: ctx.history,
          error: error,
          startedAt: ctx.startedAt,
          completedAt: ctx.completedAt,
          pausedAt: ctx.pausedAt
        };
}

function recordState(ctx, state) {
  return {
          workflowId: ctx.workflowId,
          workflowName: ctx.workflowName,
          variables: ctx.variables,
          steps: ctx.steps,
          currentStepIndex: ctx.currentStepIndex,
          history: Belt_Array.concat(ctx.history, [state]),
          error: ctx.error,
          startedAt: ctx.startedAt,
          completedAt: ctx.completedAt,
          pausedAt: ctx.pausedAt
        };
}

function getCompletedSteps(ctx) {
  return Belt_Array.keep(ctx.steps, (function (step) {
                return step.status === "Completed";
              }));
}

function getFailedSteps(ctx) {
  return Belt_Array.keep(ctx.steps, (function (step) {
                return step.status === "Failed";
              }));
}

function getPendingSteps(ctx) {
  return Belt_Array.keep(ctx.steps, (function (step) {
                return step.status === "Pending";
              }));
}

function isComplete(ctx) {
  return ctx.currentStepIndex >= ctx.steps.length;
}

function hasFailed(ctx) {
  return Belt_Array.some(ctx.steps, (function (step) {
                return step.status === "Failed";
              }));
}

var Context = {
  make: make$1,
  setVariable: setVariable,
  getVariable: getVariable,
  updateStep: updateStep,
  getCurrentStep: getCurrentStep,
  advanceStep: advanceStep,
  setError: setError,
  recordState: recordState,
  getCompletedSteps: getCompletedSteps,
  getFailedSteps: getFailedSteps,
  getPendingSteps: getPendingSteps,
  isComplete: isComplete,
  hasFailed: hasFailed
};

function isValid(transition) {
  var match = transition.from;
  var match$1 = transition.event;
  var match$2 = transition.to;
  switch (match) {
    case "Idle" :
        if (typeof match$1 === "object") {
          if (match$2 === "Failed") {
            return true;
          } else {
            return false;
          }
        }
        switch (match$1) {
          case "Start" :
              if (match$2 === "Parsing") {
                return true;
              } else {
                return false;
              }
          case "Cancel" :
              if (match$2 === "Cancelled") {
                return true;
              } else {
                return false;
              }
          default:
            return false;
        }
    case "Parsing" :
        if (typeof match$1 === "object") {
          if (match$2 === "Failed") {
            return true;
          } else {
            return false;
          }
        }
        switch (match$1) {
          case "Parse" :
              if (match$2 === "Validating") {
                return true;
              } else {
                return false;
              }
          case "Cancel" :
              if (match$2 === "Cancelled") {
                return true;
              } else {
                return false;
              }
          default:
            return false;
        }
    case "Validating" :
        if (typeof match$1 === "object") {
          if (match$2 === "Failed") {
            return true;
          } else {
            return false;
          }
        }
        switch (match$1) {
          case "Validate" :
              if (match$2 === "Executing") {
                return true;
              } else {
                return false;
              }
          case "Cancel" :
              if (match$2 === "Cancelled") {
                return true;
              } else {
                return false;
              }
          default:
            return false;
        }
    case "Executing" :
        if (typeof match$1 === "object") {
          if (match$2 === "Failed") {
            return true;
          } else {
            return false;
          }
        }
        switch (match$1) {
          case "Execute" :
              if (match$2 === "Executing") {
                return true;
              } else {
                return false;
              }
          case "Pause" :
              if (match$2 === "Paused") {
                return true;
              } else {
                return false;
              }
          case "Complete" :
              if (match$2 === "Completed") {
                return true;
              } else {
                return false;
              }
          case "Cancel" :
              if (match$2 === "Cancelled") {
                return true;
              } else {
                return false;
              }
          default:
            return false;
        }
    case "Paused" :
        if (typeof match$1 === "object") {
          if (match$2 === "Failed") {
            return true;
          } else {
            return false;
          }
        }
        switch (match$1) {
          case "Resume" :
              if (match$2 === "Executing") {
                return true;
              } else {
                return false;
              }
          case "Cancel" :
              if (match$2 === "Cancelled") {
                return true;
              } else {
                return false;
              }
          default:
            return false;
        }
    default:
      return false;
  }
}

function make$2(from, $$event, to) {
  var transition = {
    from: from,
    event: $$event,
    to: to
  };
  if (isValid(transition)) {
    return transition;
  }
  
}

var Transition = {
  isValid: isValid,
  make: make$2
};

function canStart(ctx) {
  return ctx.steps.length !== 0;
}

function canParse(_ctx) {
  return true;
}

function canValidate(_ctx) {
  return true;
}

function canExecute(ctx) {
  return !isComplete(ctx);
}

function canPause(ctx) {
  return isActive(Belt_Array.getExn(ctx.history, ctx.history.length - 1 | 0));
}

function canResume(ctx) {
  return Belt_Option.isNone(ctx.pausedAt) === false;
}

function canComplete(ctx) {
  if (isComplete(ctx)) {
    return !hasFailed(ctx);
  } else {
    return false;
  }
}

function canCancel(ctx) {
  return !isTerminal(Belt_Array.getExn(ctx.history, ctx.history.length - 1 | 0));
}

function check($$event, ctx) {
  if (typeof $$event === "object") {
    return true;
  }
  switch ($$event) {
    case "Start" :
        return canStart(ctx);
    case "Parse" :
    case "Validate" :
        return true;
    case "Execute" :
        return !isComplete(ctx);
    case "Pause" :
        return canPause(ctx);
    case "Resume" :
        return canResume(ctx);
    case "Complete" :
        return canComplete(ctx);
    case "Cancel" :
        return canCancel(ctx);
    
  }
}

var Guards = {
  canStart: canStart,
  canParse: canParse,
  canValidate: canValidate,
  canExecute: canExecute,
  canPause: canPause,
  canResume: canResume,
  canComplete: canComplete,
  canCancel: canCancel,
  check: check
};

function make$3(workflowId, workflowName, steps) {
  return {
          state: "Idle",
          context: make$1(workflowId, workflowName, steps)
        };
}

function getState(machine) {
  return machine.state;
}

function getContext(machine) {
  return machine.context;
}

function transition(machine, $$event) {
  var currentState = machine.state;
  if (!check($$event, machine.context)) {
    return {
            TAG: "Error",
            _0: "Guard check failed for event: " + toString$1($$event)
          };
  }
  var nextState;
  if (typeof $$event !== "object") {
    switch ($$event) {
      case "Start" :
          nextState = "Parsing";
          break;
      case "Parse" :
          nextState = "Validating";
          break;
      case "Pause" :
          nextState = "Paused";
          break;
      case "Complete" :
          nextState = "Completed";
          break;
      case "Cancel" :
          nextState = "Cancelled";
          break;
      default:
        nextState = "Executing";
    }
  } else {
    nextState = "Failed";
  }
  var match = make$2(currentState, $$event, nextState);
  if (match === undefined) {
    return {
            TAG: "Error",
            _0: "Invalid transition from " + toString(currentState) + " with event " + toString$1($$event)
          };
  }
  var updatedContext;
  var exit = 0;
  if (typeof $$event !== "object") {
    switch ($$event) {
      case "Start" :
          var init = machine.context;
          updatedContext = {
            workflowId: init.workflowId,
            workflowName: init.workflowName,
            variables: init.variables,
            steps: init.steps,
            currentStepIndex: init.currentStepIndex,
            history: Belt_Array.concat(machine.context.history, [nextState]),
            error: init.error,
            startedAt: Date.now(),
            completedAt: init.completedAt,
            pausedAt: init.pausedAt
          };
          break;
      case "Pause" :
          var init$1 = machine.context;
          updatedContext = {
            workflowId: init$1.workflowId,
            workflowName: init$1.workflowName,
            variables: init$1.variables,
            steps: init$1.steps,
            currentStepIndex: init$1.currentStepIndex,
            history: Belt_Array.concat(machine.context.history, [nextState]),
            error: init$1.error,
            startedAt: init$1.startedAt,
            completedAt: init$1.completedAt,
            pausedAt: Date.now()
          };
          break;
      case "Resume" :
          var init$2 = machine.context;
          updatedContext = {
            workflowId: init$2.workflowId,
            workflowName: init$2.workflowName,
            variables: init$2.variables,
            steps: init$2.steps,
            currentStepIndex: init$2.currentStepIndex,
            history: Belt_Array.concat(machine.context.history, [nextState]),
            error: init$2.error,
            startedAt: init$2.startedAt,
            completedAt: init$2.completedAt,
            pausedAt: undefined
          };
          break;
      case "Complete" :
      case "Cancel" :
          exit = 1;
          break;
      default:
        updatedContext = recordState(machine.context, nextState);
    }
  } else {
    var init$3 = machine.context;
    updatedContext = {
      workflowId: init$3.workflowId,
      workflowName: init$3.workflowName,
      variables: init$3.variables,
      steps: init$3.steps,
      currentStepIndex: init$3.currentStepIndex,
      history: Belt_Array.concat(machine.context.history, [nextState]),
      error: $$event.error,
      startedAt: init$3.startedAt,
      completedAt: Date.now(),
      pausedAt: init$3.pausedAt
    };
  }
  if (exit === 1) {
    var init$4 = machine.context;
    updatedContext = {
      workflowId: init$4.workflowId,
      workflowName: init$4.workflowName,
      variables: init$4.variables,
      steps: init$4.steps,
      currentStepIndex: init$4.currentStepIndex,
      history: Belt_Array.concat(machine.context.history, [nextState]),
      error: init$4.error,
      startedAt: init$4.startedAt,
      completedAt: Date.now(),
      pausedAt: init$4.pausedAt
    };
  }
  return {
          TAG: "Ok",
          _0: {
            state: nextState,
            context: updatedContext
          }
        };
}

function canTransition(machine, $$event) {
  return check($$event, machine.context);
}

function setVariable$1(machine, key, value) {
  return {
          state: machine.state,
          context: setVariable(machine.context, key, value)
        };
}

function getVariable$1(machine, key) {
  return Js_dict.get(machine.context.variables, key);
}

function updateStep$1(machine, stepId, updateFn) {
  return {
          state: machine.state,
          context: updateStep(machine.context, stepId, updateFn)
        };
}

function getCurrentStep$1(machine) {
  return getCurrentStep(machine.context);
}

function getCompletedSteps$1(machine) {
  return getCompletedSteps(machine.context);
}

function getFailedSteps$1(machine) {
  return getFailedSteps(machine.context);
}

function getPendingSteps$1(machine) {
  return getPendingSteps(machine.context);
}

function serialize(machine) {
  var dict = {};
  dict["state"] = toString(machine.state);
  dict["workflowId"] = machine.context.workflowId;
  dict["workflowName"] = machine.context.workflowName;
  dict["currentStepIndex"] = String(machine.context.currentStepIndex);
  var variablesJson = Js_dict.fromArray(Belt_Array.map(Js_dict.entries(machine.context.variables), (function (param) {
              return [
                      param[0],
                      param[1]
                    ];
            })));
  dict["variables"] = JSON.stringify(variablesJson);
  var stepsJson = Belt_Array.map(machine.context.steps, (function (step) {
          var stepDict = {};
          stepDict["id"] = step.id;
          stepDict["status"] = statusToString(step.status);
          return stepDict;
        }));
  dict["steps"] = JSON.stringify(stepsJson);
  return dict;
}

function deserialize(dict) {
  var match = Js_dict.get(dict, "state");
  var match$1 = Js_dict.get(dict, "workflowId");
  var match$2 = Js_dict.get(dict, "workflowName");
  if (match === undefined) {
    return ;
  }
  if (match$1 === undefined) {
    return ;
  }
  if (match$2 === undefined) {
    return ;
  }
  var state = fromString(match);
  if (state === undefined) {
    return ;
  }
  var machine = make$3(match$1, match$2, []);
  return {
          state: state,
          context: machine.context
        };
}

var Machine = {
  make: make$3,
  getState: getState,
  getContext: getContext,
  transition: transition,
  canTransition: canTransition,
  setVariable: setVariable$1,
  getVariable: getVariable$1,
  updateStep: updateStep$1,
  getCurrentStep: getCurrentStep$1,
  getCompletedSteps: getCompletedSteps$1,
  getFailedSteps: getFailedSteps$1,
  getPendingSteps: getPendingSteps$1,
  serialize: serialize,
  deserialize: deserialize
};

function eventFail(error) {
  return {
          TAG: "Fail",
          error: error
        };
}

var stateIdle = "Idle";

var stateParsing = "Parsing";

var stateValidating = "Validating";

var stateExecuting = "Executing";

var statePaused = "Paused";

var stateCompleted = "Completed";

var stateFailed = "Failed";

var stateCancelled = "Cancelled";

var eventStart = "Start";

var eventParse = "Parse";

var eventValidate = "Validate";

var eventExecute = "Execute";

var eventPause = "Pause";

var eventResume = "Resume";

var eventComplete = "Complete";

var eventCancel = "Cancel";

export {
  State ,
  $$Event ,
  StepState ,
  Context ,
  Transition ,
  Guards ,
  Machine ,
  make$3 as make,
  getState ,
  getContext ,
  transition ,
  canTransition ,
  setVariable$1 as setVariable,
  getVariable$1 as getVariable,
  updateStep$1 as updateStep,
  getCurrentStep$1 as getCurrentStep,
  getCompletedSteps$1 as getCompletedSteps,
  getFailedSteps$1 as getFailedSteps,
  getPendingSteps$1 as getPendingSteps,
  serialize ,
  deserialize ,
  stateIdle ,
  stateParsing ,
  stateValidating ,
  stateExecuting ,
  statePaused ,
  stateCompleted ,
  stateFailed ,
  stateCancelled ,
  eventStart ,
  eventParse ,
  eventValidate ,
  eventExecute ,
  eventPause ,
  eventResume ,
  eventComplete ,
  eventCancel ,
  eventFail ,
}
/* No side effect */
