/**
 * Edge Case Fixtures
 * Generated by AutomatosX v8.0.0
 */

export const edgeCaseFixtures = {
  emptyWorkflow: {
    name: 'Empty Workflow',
    version: '1.0.0',
    description: 'Workflow with no steps',
    steps: [],
  },
  singleStep: {
    name: 'Single Step Workflow',
    version: '1.0.0',
    description: 'Workflow with one step',
    steps: [
      {
        id: 'only-step',
        name: 'Only Step',
        agent: 'backend',
        action: 'test',
        config: {},
      },
    ],
  },
  circularDependency: {
    name: 'Circular Dependency',
    version: '1.0.0',
    description: 'Invalid workflow with circular dependencies',
    steps: [
      {
        id: 'step-1',
        name: 'Step 1',
        agent: 'backend',
        action: 'test',
        config: {},
        dependsOn: ['step-2'],
      },
      {
        id: 'step-2',
        name: 'Step 2',
        agent: 'backend',
        action: 'test',
        config: {},
        dependsOn: ['step-1'],
      },
    ],
  },
  veryLongWorkflow: {
    name: 'Very Long Workflow',
    version: '1.0.0',
    description: 'Workflow with many steps',
    steps: Array.from({ length: 100 }, (_, i) => ({
      id: `step-${i + 1}`,
      name: `Step ${i + 1}`,
      agent: 'backend',
      action: 'test',
      config: {},
      dependsOn: i > 0 ? [`step-${i}`] : [],
    })),
  },
  parallelSteps: {
    name: 'Parallel Steps',
    version: '1.0.0',
    description: 'Workflow with all parallel steps',
    steps: Array.from({ length: 10 }, (_, i) => ({
      id: `parallel-${i + 1}`,
      name: `Parallel Step ${i + 1}`,
      agent: 'backend',
      action: 'test',
      config: {},
      dependsOn: [],
    })),
  },
};
