/**
 * Error Fixtures
 * Generated by AutomatosX v8.0.0
 */

export const errorFixtures = {
  timeout: new Error('Step execution timeout'),
  validation: new Error('Validation failed: invalid configuration'),
  dependency: new Error('Dependency not satisfied'),
  provider: new Error('Provider request failed'),
  filesystem: new Error('File not found'),
  database: new Error('Database connection failed'),
  network: new Error('Network request failed'),
};

export const expectedErrorBehaviors = {
  timeout: {
    shouldRetry: true,
    maxRetries: 3,
    backoff: 'exponential',
  },
  validation: {
    shouldRetry: false,
    failFast: true,
  },
  dependency: {
    shouldRetry: false,
    failFast: true,
  },
  provider: {
    shouldRetry: true,
    maxRetries: 3,
    backoff: 'linear',
  },
  filesystem: {
    shouldRetry: true,
    maxRetries: 2,
  },
  database: {
    shouldRetry: true,
    maxRetries: 3,
    backoff: 'exponential',
  },
  network: {
    shouldRetry: true,
    maxRetries: 5,
    backoff: 'exponential',
  },
};
